#+BEGIN_COMMENT’        =========================        ‘#+END_COMMENT
#+BEGIN_COMMENT’           EMACS ORG MODE FILE           ‘#+END_COMMENT
#+BEGIN_COMMENT’        =========================        ‘#+END_COMMENT

* emacs

** Walk-through the code

*** tags

Configure tags:

 $ cscope-indexer -r -v

Move inside function definitions and back:

- M-. : (find-tag) : find function implementation (call).
- M-* : (pop-tag-mark) : return to the previous location (caller).

*** cscope

Configure cscope:

 $ find . -name "*.[cChH]" | etags -

Find callers, function definition, function declaration, other references:

- C-c s s : find symbol.
- C-c s d : find definition.
- C-c s c : find callers.
- C-c s f : find file.
- C-c s i Find files #including a file.

*** semantic

Configure .emacs:

 (add-hook
 'c-mode-common-hook
 (lambda()
   (define-key c-mode-base-map
       (kbd "M-<right>") 'semantic-ia-fast-jump)))

 (global-set-key
  (kbd "M-<left>")
  (lambda()(interactive) (set-mark-command 4)))
  (global-set-key [M-up] 'pop-global-mark)

Enable semantic in emacs:

 M-x semantic-mode

Move around the code:

- C-c , j : semantic-complete-jump-local : jump in the function implementation locally.
- C-c , J : semantic-complete-jump : jump in the function implementation globally.
- M-<right> : semantic-ia-fast-jump : jump directly to the function implementation over the cursor.
- M-<up> OR C-x C-<SPC>: pop-global-mark : returns from the last jump point.
** magit

Stage commit and switch branching:

  M-x magit-status  => to see git status, and in the status buffer:
    s               => stage files
    u               => unstage files
    c c             => commit message (type it and...)
         C-c C-c    => actually commit
         C-c C-a    => ammend commit
    b b             => switch to another branch
    h               => help

Push and pull:
    P P     => do a git push
    F F     => do a git pull
    try to press TAB

More advanced info:
    http://daemianmack.com/magit-cheatsheet.html
