#+BEGIN_COMMENT’        =========================        ‘#+END_COMMENT
#+BEGIN_COMMENT’           EMACS ORG MODE FILE           ‘#+END_COMMENT
#+BEGIN_COMMENT’        =========================        ‘#+END_COMMENT

* emacs

** Walk-through the code

*** tags

Configure tags:

 $ cscope-indexer -r -v

Move inside function definitions and back:

  M-.   => (find-tag) : find function implementation (call).
  M-*   => (pop-tag-mark) : return to the previous location (caller).

*** cscope

Configure cscope:

 $ find . -name "*.[cChH]" | etags -

Find callers, function definition, function declaration, other references:

 C-c s s        ==> Find symbol.
 C-c s d        ==> Find global definition.
 C-c s c        ==> Find functions calling a function.
 C-c s C        ==> Find called functions (list functions called from a function).
 C-c s t        ==> Find text string.
 C-c s e        ==> Find egrep pattern.
 C-c s f        ==> Find a file.
 C-c s i        ==> Find files #including a file.
 C-c s W        ==> Find a directory.

*** semantic

Configure .emacs:

 (add-hook
 'c-mode-common-hook
 (lambda()
   (define-key c-mode-base-map
       (kbd "M-<right>") 'semantic-ia-fast-jump)))

 (global-set-key
  (kbd "M-<left>")
  (lambda()(interactive) (set-mark-command 4)))
  (global-set-key [M-up] 'pop-global-mark)

Enable semantic in emacs:

 M-x semantic-mode

Move around the code:

- C-c , j : semantic-complete-jump-local : jump in the function implementation locally.
- C-c , J : semantic-complete-jump : jump in the function implementation globally.
- M-<right> : semantic-ia-fast-jump : jump directly to the function implementation over the cursor.
- M-<up> OR C-x C-<SPC>: pop-global-mark : returns from the last jump point.

*** yasnippet
  TODO
*** abbrev
  TODO
*** Auto-complete
  TODO

** org-mode
- Tree visibility
  - TAB                => cycle tree
  - (org-global-cycle) => org global cycle

- add entries
  - C-RET         => add new heading tree
  - Alt-RET       => add new subentry
  - C-shift-RET   => add new heading todo tree
  - Alt-shift-RET => add new task todo subentry

- promote and demote
  - Alt-left  => promote
  - Alt-right => demote
  - Alt-shift-left  => promote tree
  - Alt-shift-right => demote tree
  - Alt-shift-up    => move subtree up
  - Alt-shift-down  => move subtree down

- set tasks
  - C-c C-d  => set deadline
  - C-c C-s  => set schedule
  - C-c C-c  => to close a simple task
  - C-c C-t  => to close a full set of tasks

- show tasks
  - TAB          => expand one task into subtasks
  - Shift + TAB  => expand all subtree (if multiple times expands more)

- set priorities
  - C-c , +  => increase prio
  - C-c , -  => decrease prio

- set tags
  - C-c C-q  => set a tag

- show agenda
  - C-c a a => agenda todo for current day/week
  - C-c a t => agenda todo for all the tasks
  - C-c a L => agenda todo for the current buffer
  - C-c a m => agenda todo for specific tag
  - C-c a s => agenda todo for specific search

- ORG+check
  - C-c / d  => Check deadlines
  - C-c / b  => Check schedules and deadlines
  - C-c / a  => Check deadlines after date

  - Return to original view  => "q" or just Shift+TAB until view is ok

- Show current tasks on startup (org-agenda) : check in dotemacs

** emacs-server
- Processes
 - emacs --daemon => opens a server
 - emacsclient -c => opens a client
 - emacsclient -c -n => opens a client without blocking the terminal
 - emacsclient -a => opens a client or an editor in case the server is not running
- Keys associated
 - C-x #          => close the client
 - C-x c          => closes the server or process if no server is running
 - C-x 5 0        => closes the current frame (except the last one if there is no server running, if there is, the server still running with all the buffers)

** magit

Stage commit and switch branching:

  M-x magit-status  => to see git status, and in the status buffer:
    s               => stage files
    u               => unstage files
    c c             => commit message (type it and...)
         C-c C-c    => actually commit
         C-c C-a    => ammend commit
    b b             => switch to another branch
    h               => help

Push and pull:
    P P     => do a git push
    F F     => do a git pull
    try to press TAB

More advanced info:
    http://daemianmack.com/magit-cheatsheet.html
