#+BEGIN_COMMENT’              ===================               ‘#+END_COMMENT
#+BEGIN_COMMENT’                   NUTRITION                    ‘#+END_COMMENT
#+BEGIN_COMMENT’              ===================               ‘#+END_COMMENT

* Superfood
 https://en.wikipedia.org/wiki/Freekeh
 https://en.wikipedia.org/wiki/Quinoa
 https://en.wikipedia.org/wiki/Salvia_hispanica
 https://en.wikipedia.org/wiki/Amaranth
 https://en.wikipedia.org/wiki/Bulgur
 https://en.wikipedia.org/wiki/Buckwheat
 https://en.wikipedia.org/wiki/Millet
 https://en.wikipedia.org/wiki/Kale

* Nutrition [/]                                                  :2016:nutrition:
** [#A] Tasks [16%]
   SCHEDULED: <2015-06-06 Sat>
 - [ ] Register description of type of ingest
 - [X] Register IDR
 - [ ] Track IDR
 - [ ] Complete oligoelements with this [[http://es.wikipedia.org/wiki/Oligoelemento]]
 - [ ] Complete vitamins with this [[http://en.wikipedia.org/wiki/Vitamin]]
 - [-] Check huge list of links
   - [ ] Essential aminoacids and quantity: http://www.whfoods.com/genpage.php?tname=nutrient&dbid=129
   - [ ] https://es-la.facebook.com/notes/yo-no-como-cad%C3%A1veres-respet%C3%A1-los-derechos-de-los-animales/una-mirada-cient%C3%ADfica-de-porque-no-comer-carne/311347328881727
   - [ ] La revolución comienza por tu menú del día http://www.meneame.net/story/revolucion-comienza-tu-menu-dia
   - [ ] "Dejar de comer carne salva el Planeta" dice Naciones Unidas [ING] http://www.meneame.net/story/dejar-comer-carne-salva-planeta-dice-naciones-unidas-ing
   - [ ] Receta de WWF para salvar la Tierra: energías renovables y menos consumo de carne http://www.wwf.es/?16501/Receta-de-WWF-para-salvar-la-TierraMs-energas-renova
   - [ ] Comer carne y lácteos compromete el objetivo de limitar el calentamiento global a 2ºC: http://www.meneame.net/story/producir-carne-lácteos-compromete-objetivo-limitar-calentamiento
   - [ ] Greenpeace demuestra cómo la ganadería es la primera causa de deforestación en la amazonía: http://www.meneame.net/story/greenpeace-demuestra-como-ganaderia-primera-causa-deforestacion-amazon
   - [ ] Estamos destruyendo el amazonas para alimentar vacas http://www.elpais.com/articulo/sociedad/Estamos/destruyendo/Amazonas/alimentar/vacas/elpepusoc/20080627elpepisoc_9/Tes
   - [ ] La 'industria' de la carne contamina más que el transporte: http://www.elmundo.es/elmundo/2010/07/20/valencia/1279645414.html
   - [ ] Un ciclista carnívoro contamina lo mismo que un vegetariano en un 4x4: http://www.reducetuhuella.org/2010/08/16/un-ciclista-carnivoro-contamina-lo-mismo-que-un-vegetariano-en-un-4x4-diesel/
   - [ ] España es el 8º país que más carne consume del planeta : http://www.meneame.net/story/grafico-consumo-carne-mundo-espana-octavo-pais-mas-carnivoro
   - [ ] http://www.forovegetariano.org/foro/showthread.php?t=10808 (lista completa):
   - [ ] Los Campos de la Muerte. La batalla para alimentar la ganadería industrial [Documental]: http://www.meneame.net/story/campos-muerte-batalla-alimentar-ganaderia-industrial-documental-1
   - [ ] Ditto: http://www.youtube.com/watch?v=RF31mHrf9fM
   - [ ] Se requieren 15.000 litros de agua para generar un kilo de carne, señala la FAO: http://www.todoagro.com.ar/noticias/nota.asp?nid=19709
   - [ ] Se ahorra más agua no comiendo carne que no bañándose: http://www.meneame.net/story/ahorra-mas-agua-no-comiendo-carne-no-banandose
   - [ ] Consumo de agua de diferentes alimentos: http://www.waterfootprint.org/?page=files/productgallery&product=apple
   - [ ] Documentos TV: "Ámame enCARNEcidamente"
     - [ ] El desmesurado consumo de carne ha abierto la puerta a la ganadería industrial
     - [ ] En la actualidad se sacrifican 60.000 millones de animales para alimentarnos
     - [ ] Si la demanda de carne sigue la progresión actual, la cifra se duplicará en 2050
     - [ ] Este insostenible sistema provoca estragos en la salud y el Medio Ambiente
   - [ ] http://www.rtve.es/television/20120529/documentos-amame-encarnecidamente/5321
   - [ ] Cutting red meat-for a longer life: http://www.health.harvard.edu/staying-healthy/cutting-red-meat-for-a-longer-life
   - [ ] Red meat consumption and breast cáncer risk women who ate the most red meat in adolescence or early adulthood had an increased risk of developing breast cáncer later in life.: http://www.hsph.harvard.edu/news/features/red-meat-consumption-and-breast-cáncer-risk/
   - [ ] Red meat raises red flags red meat consumption is associated with an increased risk of total, cardiovascular, and cáncer mortality.: http://news.harvard.edu/gazette/story/2012/03/red-meat-raises-red-flags/
   - [ ] Red meat consumption linked to increased risk of total, cardiovascular, and cáncer mortality: http://www.hsph.harvard.edu/news/press-releases/red-meat-consumption-linked-to-increased-risk-of-total-cardiovascular-and-cáncer-mortality/
   - [ ] Post punk kitchen: http://www.theppk.com/
   - [X] Post lots of vitamins info: https://ods.od.nih.gov/factsheets/list-VitaminsMinerals/
   - [X] Additional vitamins info incompatible: http://www.katking.com/Wisdom/Vitamin.html
 - [ ] Polifenoles
 - [ ] Limonoides

** [#B] Info
*** General basic info
 Los principales macronutrientes son:

  - Proteínas: son moléculas formadas por cadenas lineales de aminoácidos (Un aminoácido es una molécula orgánica con un grupo amino (-NH2) y un grupo carboxilo (-COOH)). La unión entre aminoácidos se llaman uniones peptídicas.

    Ejemplo de aminoácido:

                  H
                  | / El carbono es alfa
    Grupo amino - C - Grupo Carboxilo
      (H2N)       |      (COOH)
                  R
           (cadena lateral)

    Como se forma la unión peptídica:

      H    H      0        H    H      0
       \   |    //          \   |    //
       N - C - C            N - C - C
       /   |    \           /   |    \
      H    R     O - H     H    R      O - H
                 \----------/
               unión peptídica
               formando agua, uniéndose así
               el carbono con el nitrógeno

      -> Se llama "péptido" Cuando se unen pocos aminoácidos (2 dipéptido, 3 tripéptido... etc. Menos de 10 se les puede llamar oligopéptido).
      -> De 10 a 50 (polipéptido)
      -> Mas de 50 (se llama proteína propiamente dicha). Aunque a todas se les llaman proteínas.
      -> Las proteínas tienen un orden especifico de aminoácidos (estructura primaria) y de ahí reciben su nombre.
      -> Estructura secundaria: la disposición de la proteína que adopta en el espacio dentro de las células (puede ser en hoja o beta-sheet, helice o alfa-helix -formadas por puentes di-isulfuro (S-S), puentes de hidrógeno (O-H...O), puentes iónicos (moléculas con carga positiva y carga negativa) y las interacciones hidrofóbicas (dos moléculas que rechazan el agua y quedan unidas entre sí)-, llamada también alfa, porque se descubrió primero,... o podria ser Random coil o configuración al azar es sin ninguna forma especifica).
      -> Estructura terciaria: es el nuevo plegamiento o sobreenrollamiento que una proteína tiene con una estructura secundaria.
      -> Estructura cuaternaria: a estructura cuaternaria se da cuando se unen varias proteínas en conformación 3D(es decir, con estructura terciaria). A cada proteína se le denomina subunidad y suelen ser todas iguales.

    Las proteínas son necesarias por:
    * Estructural: Esta es la función más importante de una proteína (Ej. colágeno). Constituyendo el 80% del protoplasma deshidratado de todas las células.
    * Inmunológica: anticuerpos.
    * Enzimática: por ejemplo sacarasa y pepsina.
    * Contráctil: actina y miosina.
    * Homeostática: colaboran en el mantenimiento del pH (ya que actúan como un tampón químico).
    * Transducción de señales: por ejemplo rodopsina.
    * Protectora o defensiva: por ejemplo trombina y fibrinógeno.
    * Producción de costras: por ejemplo fibrina.

    Se pueden categorizar según propiedades fisico-químicas:
    * Holoproteidos: proteínas simples formadas solo por aminoácidos o sus derivados.
    * Heteroproteidos: proteínas conjugadas formadas por aminoácidos acompañados de distintas sustancias

    Se pueden categorizar según su forma:
    * Fibrosas: cadenas polipeptídicas largas y una estructura secundaria atípica.
    * Globulares: cadenas en una forma esférica apretada o compacta.
    * Mixtas: posee una parte fibrilar (comúnmente en el centro de la proteína) y otra parte globular (en los extremos).

    Se pueden categorizar según su solubridad:
    * Escleroproteínas: son esencialmente insobles, fibrosas y cristalinidad alta.
    * Esferoproteínas: de forma mas o menos esférica, hay 5 tipos según su solubilidad:
      - I: Albuminas: solubles en agua y soluciones salinas diluidas.
      - II: Globulinas: insolubles en agua pero solubles en soluciones salinas.
      - III: Glutelinas: insolubles en agua o soluciones salinas, pero solubles en medios ácidos o básicos.
      - IV: Prolaminas: solubles en etanol al 50%-80%.
      - V: Histonas: son solubles en medios ácidos.

    Se pueden categorizar según su origen (tantos uno como otro tipo poseen los 20 aminoácidos necesarios para la alimentación humana):
    * Origen vegetal: legumbres, frutos secos, semillas, cereales, verduras
    * Origen animal: carne, huevos, productos lácteos

  - Grasas (Lípidos): compuestos principalmente por carbono e hidrógeno y en menor medida oxígeno, aunque también pueden contener fósforo, azufre y nitrógeno. Son hidrófobas (no solubles en agua). Cumplen funciones diversas en los organismos vivientes, entre ellas la de reserva energética (como los triglicéridos), la estructural (como los fosfolípidos de las bicapas) y la reguladora (como las hormonas esteroides).
    * Saponificables: lípidos que se hidrolizan en presencia de hidróxidos. Están compuestos por un alcohol unido a uno o varios ácidos grasos.
        -> Simples: los que contienen carbono, hidrógeno y oxígeno.

           * Saturadas: todos los carbonos poseen dos enlaces con hidrógenos, por lo que los enlaces entre carbonos son simples.
           * Insaturadas: existen carbonos que no tienen dos enlaces con hidrógenos, por lo que existen enlaces dobles o triples entre carbonos (estos dobles enlaces crean una inclinación en la molécula).

             Por numero de enlaces:
             -> Mono-insaturadas: poseen un solo doble enlace carbono-carbono

             -> Poli-insaturadas: poseen más de un doble enlace entre sus carbonos (incluso puede ser triple)
                * Omega 3: el primer enlace doble esta situado en la posición 3. Existiendo 6 subtipos:
                           - Ácido alfa-linolénico (ALA): 18:3 (n-3):
                           - Ácido estearidónico (SDA): 18:4 (n-3):
                           - Ácido eicosatetraenoico (ETA): 20:4 (n-3)
                           - Ácido eicosapentaenoico (EPA): 20:5 (n-3):
                           - Ácido docosapentaenoico (DPA): 22:5 (n-3)
                           - Ácido docosahexaenoico (DHA): 22:6 (n-3)
                * Omega 6: el primer enlace doble esta situado en la posición 6. Omega-6 compite con omega-3 en el organismo humano.
                * Omega 9: el primer enlace doble esta situado en la posición 9 (pero NO es poliinsaturado, sino monoinsaturado porque solo posee un enlace doble).

             Por tipo de configuración o estructura molecular:
             -> Cis: los enlaces de hidrógenos hacia los carbonos están en un mismo lado (en donde se encuentra el enlace doble).
             -> Trans: los enlaces de hidrógenos hacia los carbonos están en lados opuestos (en donde se encuentra el enlace doble).

             Por dios sabe que:
                                                          O                 OH OH OH
                                                          ||                 | | |
             -> Gliceridos: unión entre ácidos grasos (HO-C-R) y glicerol (H-C-C-C-H). El triglicérido seria que una molécula de ácidos grasos se uniese a tres gliceroles (los triglicéridos se depositan principalmente en las arterias cerebrales).
                                                                             | | |
                                                                             H H H
                * Grasas:
                * Aceites:
             -> Ceras:


        -> Complejos: los que contienen carbono, hidrógeno, oxigeno y otros elementos como nitrógeno, fósforo, azufre u otra biomolécula como un glúcido. O lo que es lo mismo, seria un lípido unido con "otra sustancia" (fósforo, se llamaría fosfolípido. Glucosa, se llamaría "glucolípido", proteína, se llamaría "proteolípido")

           * Fosfolípidos: lípidos anfipáticos compuestos por una molécula de glicerol, a la que se unen dos ácidos grasos (1,2-diacilglicerol) y un grupo fosfato.
             Funciones: Componente estructural de la membrana celular, Activación de enzimas, Componentes del surfactante pulmonar, Componente detergente de la bilis, Síntesis de sustancias de señalización celular.
           * Fosfoglicéridos: Están compuestos por ácido fosfatídico, una molécula compleja compuesta por glicerol, en el que se han esterificado dos ácidos grasos (uno saturado y otro insaturado) y un grupo fosfato. A su vez, al grupo fosfato se une un alcohol o un aminoalcohol.
             Funciones: función estructural.
           * Fosfoesfingolípidos:  lípidos complejos que derivan del aminoalcohol insaturado de 18 carbonos esfingosina los hay con fosfato. Se dividen en 2 subtipos: fosfoesfingolípidos (esfingomielinas) y los glucoesfingolípidos (gangliósidos, cerebrósidos).
             Funciones: desempeña una función en la transducción de señales. La vaina de mielina membranosa que rodea y aísla eléctricamente muchos axones de células nerviosas es particularmente rica en esfingomielina, lo que parece indicar que su función es mejorar el aislamiento de las fibras nerviosas.
             * Glucolípidos: son esfingolípidos compuestos por una ceramida (esfingosina + ácido graso) y un glúcido de cadena corta; carecen de grupo fosfato.
               Funciones: es un componente fundamental del glicocálix, donde actúa en el reconocimiento celular y como receptor antigénico.
             * Cerebrósidos: constan de una molécula de ceramida (esfingosina + ácido graso) a la que se une un monosacárido mediante enlace β-glucosídico en el grupo hidroxilo de la ceramida. El monosacárido puede ser tanto glucosa como galactosa, lo que origina dos familias de cerebrósidos
               Funciones: forman parte de la vaina de mielina de los nervios.
             * Gangliósidos: on glucolípidos con cabezas polares muy grandes formadas por unidades de oligosacáridos cargadas negativamente, y que poseen una o más unidades de ácido N-acetilneuramínico o ácido siálico que tiene una carga negativa a pH 7.
               Funciones: Se presentan en la zona externa de la membrana y sirven para reconocer las células, por lo tanto se les considera receptores de membrana.
           Mas información en: https://es.wikipedia.org/wiki/L%C3%ADpido

        -> Asociados: químicamente no son lípidos, pero con propiedades similares, ubicandolos así en este grupo.
           * esteroides: Presencia en común de la molécula de ciclopentanoperhidrofenantreno por ej. hormonas sexuales, vitamina D, colesterol, etc. Muy comunes en la biología de los mamíferos y la humana.

           * carotenoides:
           * ubiquinona:
           * tocoferol: vitamina E.
           * filoquinona: vitamina K.

    * Insaponificables: lípidos que no se hidrolizan en presencia de hidróxidos

           * Terpenoides: son lípidos derivados del hidrocarburo isopreno (o 2-metil-1,3-butadieno). Los terpenos son el principal constituyente de los aceites esenciales de algunas plantas y flores, como el limonero, el naranjo.
           * Esteroides: son lípidos derivados del núcleo del hidrocarburo esterano (o ciclopentanoperhidrofenantreno), esto es, se componen de cuatro anillos fusionados de carbono que posee diversos grupos funcionales (carbonilo, hidroxilo) por lo que la molécula tiene partes hidrofílicas e hidrofóbicas (carácter anfipático). Entre los esteroides más destacados se encuentran los ácidos biliares, las hormonas sexuales, las corticosteroides, la vitamina D y el colesterol.
           * Eicosanoides: son lípidos derivados de los ácidos grasos esenciales de 20 carbonos tipo omega-3 y omega-6. Los principales precursores de los eicosanoides son el ácido araquidónico, el ácido linoleico y el ácido linolénico.
           Mas información en: https://es.wikipedia.org/wiki/L%C3%ADpidos_insaponificables

  - Carbohidratos/glúcidos: suministran energía, realizan un papel vital para la digestión, la asimilación, metabolismo y la oxidación de proteínas y grasas.
    * Simples: azucares que se componen de 1 o 2 azucares (no contiene nutrientes esenciales o muy pocas vitaminas y minerales)

      -> Monosacárido: (CH2O)n (donde n es cualquier número igual o mayor a tres, su límite es de 7 carbonos). Los monosacáridos poseen siempre un grupo carbonilo en uno de sus átomos de carbono y grupos hidroxilo en el resto, por lo que es un polialcohol. Los monosacáridos se clasifican de acuerdo a tres características diferentes: la posición del grupo carbonilo, el número de átomos de carbono que contiene y su quiralidad.

         Por la posición del grupo carbonilo:
         * Aldosa: cuando el carbonillo es aldehído.
         * Cetosa: cuando el carbonillo es cetona.
         * etc... checkear todos los carbonilos: https://es.wikipedia.org/wiki/Grupo_carbonilo

         Por numero átomos de carbono:
         * Diosa: los que poseen dos átomos de carbono (como es menor de 3 NO es un monosacárido).
         * Triosas: los que poseen tres átomos de carbono.
         * Tetrosas: los que poseen cuatro átomos de carbono.
         * Pentosas: los que poseen cinco átomos de carbono.
         * Hexosas: los que poseen seis átomos de carbono.
         * Heptopsa: los que poseen siete átomos de carbono.

         Por quiralidad:
         Cada átomo de carbono posee un grupo de hidroxilo (-OH), con la excepción del primero y el último carbono, todos son asimétricos, haciéndolos centros estéricos con dos posibles configuraciones cada uno (el -H y -OH pueden estar a cualquier lado del átomo de carbono). Debido a esta asimetría, cada monosacárido posee un cierto número de isómeros.
         Se mide la orientación del carbono asimétrico mas alejado del grupo carbonilo:
         * Azúcar D: Si el grupo hidroxilo está a la derecha de la molécula.
         * Azúcar L: Si el grupo hidroxilo está a la derecha de la molécula.
         Como los D azúcares son los más comunes, usualmente la letra D es omitida.

      -> Disacárido: Los disacáridos son glúcidos formados por dos moléculas de monosacáridos. Los dos monosacáridos se unen mediante un enlace covalente conocido como enlace glucosídico.
         * Sacarosa: compuesto de una molécula de glucosa y una molécula de fructosa. La glucosa adopta la forma piranosa y la fructosa una furanosa. El carbono anomérico uno (C1) de α-glucosa está enlazado en alfa al C2 de la fructosa formando 2-O-(alfa-D-glucopiranosil)-beta-D-fructofuranosido. El carbono anomérico de ambos monosacáridos participan en el enlace glicosídico.
         * Lactosa: compuesto por una molécula de galactosa y una molécula de glucosa. Esta solo presente en la leche de forma natural.
         * Maltosa: formado por dos glucosa con enlace α-1,4; se obtiene de la hidrólisis del almidón.
         * Celobiosa: formado dos glucosas con enlace β-1,4; se obtiene de la hidrólisis de la celulosa.

    * Compuestos: estructura de tres o mas azucares. Ricos en fibra, vitaminas y minerales. No aumentan tan rápido los niveles de azúcar en sangre (al ser mas complejos).
    La parte no utilizada se almacena en el hígado o se convierte en grasa.

      -> Oligosacárido: Los oligosacáridos están compuestos por tres a nueve moléculas de monosacáridos. Se encuentran con frecuencia unidos a proteínas, formando las glucoproteínas.
      -> Polisacárido: Los polisacáridos son cadenas de más de diez monosacáridos.
         * Almidon: es la manera en que las plantas almacenan monosacáridos (amilosa + amilopectina).
         * Glucogeno: es empleado por los animales, permitiendo ser metabolizado mas rápidamente (ajustándose a los animales en vida de locomoción).
         * Celulosa: forma la pared celular de las plantas.
         * Quitina: empleado en el exoesqueleto de los artrópodos y en las paredes celulares de muchos hongos. Similar a la celulosa pero empleando hidrógeno en sus ramas incrementando así su fuerza.
         * Calosa: se encuentra en los plasmodesmos durante la citocinesis y durante el desarrollo del polen.
         * Laminarina: se encuentra en anti-apoptosis (muerte de las células) y actividades anti-tumores
         * Maltodextrina: es el resultado de la hidrólisis del almidón o la fécula (ideal para actividades físicas intensas y de larga duración debido a su liberación gradual de glucosa en sangre).
         * Xilano: se encuentra en la corteza de los arboles y en la paja.
         * Galactomanosa: galacto-polisacárido (sin información).

  - Vitaminas: Las vitaminas son precursoras de coenzimas, (aunque no son propiamente enzimas) grupos prostéticos de las enzimas. Esto significa que la molécula de la vitamina, con un pequeño cambio en su estructura, pasa a ser la molécula activa, sea ésta coenzima o no. Actúan como catalizadoras de todos los procesos fisiológicos (directa e indirectamente).
    * Liposolubles: solubles en lípidos
      - Vitamina A: C20H30O. Resistencia a infecciones, la producción de anticuerpos, crecimiento óseo, fertilidad. Pero su principal función es la que cumple en la retina.
      - Vitamina D: Absorción de minerales y la mineralización de hueso marca lo importante que es para la densidad ósea.
      - Vitamina E: C27H46O2. Antioxidante que posee la propiedad de proteger a los ácidos grasos poliinsaturados de las membranas y otras estructuras celulares de la peroxidación lipídica.
      - Vitamina K: La vitamina K convierte proteínas Glu en Gla, carboxilación que ocurre dentro de la célula.
    * Hidrosolubles: solubles en aguas
      - Vitamina B1: C12H17N4OS+.  juega un papel importante en el metabolismo de carbohidratos principalmente para producir energía; además de participar en el metabolismo de grasas, proteínas y ácidos nucleicos (ADN, ARN). Es esencial para el crecimiento y desarrollo normal y ayuda a mantener el funcionamiento propio del corazón, sistema nervioso y digestivo. Ademas protege a las células ante los niveles elevados de glucosa.
      - Vitamina B2: Necesaria para la integridad de la piel, las mucosas y de forma especial para la córnea, por su actividad oxigenadora, siendo imprescindible para la buena visión. Su requerimiento se incrementa en función de las calorías consumidas en la dieta: a mayor consumo calórico, mayor es la necesidad de vitamina B2. Esta vitamina es crucial para la producción de energía en el organismo. Otra de sus funciones consiste en desintoxicar el organismo de sustancias nocivas, además de participar en el metabolismo de otras vitaminas
      - Vitamina B3: C6H5NO2. Las formas coenzimáticas de la niacina participan en las reacciones que generan energía gracias a la oxidación bioquímica de hidratos de carbono, grasas y proteínas. NAD+ y NADP+ son fundamentales para utilizar la energía metabólica de los alimentos. La niacina participa en la síntesis de algunas hormonas y es fundamental para el crecimiento. Además de funciones biológicas como: mantener el buen estado del sistema nervioso, producir neurotransmisores, mejorar el sistema circulatorio relajando los vasos sanguíneos, mantener una piel sana, estabilizar la glucosa en la sangre y restaurar el ADN.
      - Vitamina B5: Esta coenzima puede actuar como un grupo transportador de acilos para formar acetil-CoA y otros componentes relacionados; ésta es una forma de transportar átomos de carbono dentro de la célula. La transferencia de átomos de carbono por la CoA es importante en la respiración celular, así como en la biosíntesis de muchos compuestos importantes como ácidos grasos, colesterol y acetil colina. Interviene en una amplia variedad de procesos celulares entre los que se encuentran pasos de traducción de la señal.
      - Vitamina B6: Sirve de coenzima para múltiples enzimas, interviene en el metabolismo de neurotransmisores que regulan el estado de ánimo, como la serotonina, pudiendo ayudar, en algunas personas, en casos de depresión, estrés y alteraciones del sueño. Además interviene en la síntesis de dopamina, adrenalina, norepinefrina y GABA (ácido gamaaminobutírico), un neurotransmisor inhibitorio muy importante del cerebro. incrementa el rendimiento muscular y la producción de energía. Eso es debido a que cuando hay necesidad de un mayor esfuerzo favorece la liberación de glucógeno que se encuentra almacenado en el hígado y en los músculos. También puede colaborar a perder peso ya que ayuda a que nuestro cuerpo consiga energía a partir de las grasas acumuladas. importante para una adecuada absorción de la vitamina B12 y del magnesio. Alivia las náuseas. ayuda en caso de tendencia a espasmos musculares nocturnos, calambres en las piernas y adormecimiento de las extremidades. Puede ayudar a reducir la sequedad de boca ocasionada por la toma de medicamentos y/o drogas. Interviene en la síntesis de ADN y ARN. Mantiene el funcionamiento de las células nerviosas ya que interviene en la formación de mielina. Favorece la absorción de hierro.
      - Vitamina B7/B8: C10H16N2S3. La biotina se encuentra en la célula unida con resto específico de lisina (un aminoácido) formando la biocitina; la biocitina se une covalentemente a ciertas enzimas relacionadas con la formación o la utilización del dióxido de carbono, y ejerce así función de coenzima: actúa en la transferencia (aceptor y donador) de dióxido de carbono en numerosas carboxilasas y decarboxilasas, que son esenciales en los procesos de duplicación celular.  es usada en el crecimiento celular, la producción de ácidos grasos y en el metabolismo de grasas y aminoácidos. Juega un papel en el ciclo del ácido cítrico o Krebs, el cual es un proceso por el cual la energía bioquímica es generada durante la respiración aeróbica. La biotina no sólo asiste en varias conversiones químicas y metabólicas, sino también ayuda a transferir dióxido de carbono. La biotina participa también en el mantenimiento de los niveles de azúcar en la sangre o glucemia.
      - Vitamina B9: C19H19N7O6. La vitamina B9 ayuda a convertir la vitamina B12 en una de sus formas coenzimáticas y participa en la síntesis de ADN requerido para un rápido crecimiento celular. Del mismo modo actúa como coenzima en la transferencia de grupos monocarbonados. Interactúa con B12 y Vit C. El ácido fólico no posee actividad coenzimática, pero sí su forma reducida, el ácido tetrahidrofólico, representado frecuentemente como FH4 o TFH. Actúa como transportador intermediario de grupos con un átomo de carbono, especialmente grupos formilo, que se precisa en la síntesis de purinas, compuestos que forman parte de los nucleótidos, sustancias presentes en el ADN y el ARN, y necesarias para su síntesis durante la fase S del ciclo celular, y por lo tanto para la división celular; también actúa en la transferencia de grupos metenilo y metileno. El ácido tetrahidrofólico también actúa en la ruta de las pirimidinas, al modificar el anillo de uridina para formar la tiamina al ceder un grupo metilo. Las coenzimas de vitamina B9 (H4 folato) desempeñan un papel vital en el metabolismo del ADN a través de la síntesis de ADN a partir de sus precursores (timidina y purinas) y la síntesis del aminoácido metionina, que es necesario para la síntesis de un donante del grupo metilo utilizado en muchas reacciones biológicas. La adición de un grupo metilo (-CH3) (‘metilación’) en un número de puntos del ADN podría tener importancia en la prevención del cáncer. Las coenzimas del folato son necesarias para el metabolismo de diversos aminoácidos importantes, como la síntesis de metionina a partir de la homocisteína. La vitamina B9 (ácido fólico) regula la cantidad de homocisteína en la sangre, aunque lo hacen también las vitaminas B6 y B12 (4). Se ha observado que es la B9 la que tiene el mayor efecto en la reducción del nivel basal de homocisteína en la sangre cuando no hay una deficiencia coexistente de vitamina B6 ó B12.
      - Vitamina B12: C63H88CoN14O14P. intervienen en la metilación de la homocisteína a metionina y en la síntesis de S-Adenosil metionina. necesaria para la metilación de los fosfolípidos de la vaina de mielina. ayuda en el reciclado para la provisión de un sustrato adecuado para este (el aminoácido esencial metionina) ya que es asistido por la B12. La S-Adenosil metionina está involucrada en de numerosas reacciones de metilación que implican proteínas, fosfolípidos, ADN, el metabolismo de ciertos neurotransmisores, catecolaminas y en el metabolismo del cerebro.23 Estos neurotransmisores son importantes para mantener el buen estado de ánimo, lo que posiblemente explica por qué la depresión está asociada con la deficiencia de B12.
      - Notas sobre la Vitamina B12: Ningun animal, planta, hongo o alga pueden generar la vitamina B12, ya que esta solo se produce por fermentacion de bacterias y arqueobacterias que tienen las enzimas necesarias para su sintesis, aunque algunos alimentos debido a su sintesis bacteriana son generalmente fuentes de esta vitamina. Para la absorción de esta vitamina se necesitan principalmente dos procesos; el primero es la separacion de la vitamina del resto de alimentos, mediante el ácido clorhidrico en el estomago. Y el segundo, mediante el factor intrinseco gastrico, que es una glucoproteína producida por las células parietales de la mucosa gastrica (estomago) necesaria para la absorción intestinal de la vitamina B12 (realizando el transporte ileal para mas tarde llegar a la circulación sanguínea). La vitamina B12 puede almacenarse en el hígado por mas de 1 año sin deficiencias, lo que hace que la avitaminosis en este caso sea un caso muy raro.
      - Vitamina C: C6H8O6. Sirve para: Evitar el envejecimiento prematuro, Facilitar la absorción de otras vitaminas y minerales, como antioxidante, Evitar las enfermedades degenerativas tales como arteriosclerosis, cáncer, demencia, entre otros, Evitar las enfermedades cardíacas, Tiene un papel fundamental en la formación de colágeno, Prevenir escorbuto, polio y hepatitis, Disminuir la incidencia de coágulos en las venas, Ayudar en los movimientos articulares, Acelerar el proceso de curación de heridas, lesiones y quemaduras.
    * Incompatibilidades (-) y aceleracion (+) de la absorción de vitaminas
      - Vitamina A:
        - Aspirina (ácido acetilsalicilico)
        - Ácido clorihidrico.
        - Altas concentraciones de vitamina E reducen la absorción de vitamina A.
        + La vitamina A ayuda a la absorción de la vitamina E.
        + El zinc ayuda a una mejor absorción de vitamina A.
      - Vitamina D:
        - Incompatible con la vitamina E.
        - Incompatible con hidrocortisona, tetracycline, ácido hydrochloric.
        - Cuidado con las mujeres mayores, y embarazadas mayores de 35 anos.
        + Efecto positivo en el metabolismo del cuerpo en el calcio y fosforo.
      - Vitamina E:
        - Incompatible con la vitamina D.
      - Vitamina K
        - Tomarla separada de la A.
        - Tomarla separada de la E.
      - Vitamina B1:
        - Calcio (ya que reduce la que se disuelva la vitamina B1 en agua).
        - Magnesio (ya que reduce la que se disuelva la vitamina B1 en agua).
        + Generalmente se absorbe con B6, B12, C y B3.
      - Vitamina B2:
        - Hierro.
        - Zinc.
        - Cobre.
        + B6 (acelera el proceso).
        + Con la B12 ambas varian el metabolismo.
      - Vitamina B3:
        - Incompatible con tetracycline, hydrocortisone, aminophylline y otros.
        - Vitamina B1.
        - Vitamina B3 (incrementa el nivel de ciertas enzimas en la sangre causando FLD o esteatosis hepatica -grasa en el hígado-).
        - Vitamina B6.
        - Vitamina B12.
        - No recomendada para diabeticos.
        + Mejor tomarla despues de las comidas.
      - Vitamina B5:
        ??????????
      - Vitamina B6:
        - Cafeina.
        - Aminofilina.
        - B1.
        - B12.
        - Con precaucion si se tienen ulceras gastricas o duodenales.
        + B2 (acelera la asimilación de magnesio).
      - Vitamina B7/B8:
        ??????
      - Vitamina B9:
        + C.
        - Zinc (inhibe la absorción de ambas; tanto zinc como la B9).
        - Ancianos con cáncer deben ser precavidos.
      - Vitamina B12:
        - Aspirina (ácido acetilsalicilico)
        - Ácido clorihidrico.
        - Clorpromazina.
        - Gentamicina.
        - C.
        - B1 (creando reacciones alergicas).
        - B2.
        - B3.
        - B6.
        - Con precauciones por angina, tumores (tanto benignos como malignos).
      - Vitamina C:
        - Tetracycline
        - Diphenhydramine
        - Penicilina
        - Aminophylline
        - Preparados de hierro.
        - B1.
        - B12.
        - No se puede introducir por medio de inyecciones mexclandolo con analgium.
        - En muchos casos, la absorción de esta vitamina crea deficiencia de cobre.
        + Se acelera la absorción mediante Flavonoides (vitamina P).
        + E (interacciona bien).
        + Carotenos
        + Mejora la absorción de hierro, cromo.
    * Notas importantes:
    ! No hay que preocuparse por la falta de vitaminas, porque se necesitan miligramos y en algunos casos microgramos y las dietas son suficientemente variadas para obtener todas las vitaminas y enzimas que modulan el metabolismo de la tirosina.
    ! Las vitaminas antioxidantes son especialmente las A, C, y E. Con especial peligro en el exceso de vitamina A que causa osteoporosis.
    ! Las vitaminas y multivitaminas deben tomarse despues de las comidas para evitar efectos secundarios (como el impacto en órganos o en el tracto intestinal)
    ! Las vitaminas que se introduzcan por jeringa, nunca deben estar mezcladas.
    ! Antes de tomarse preparados multivitaminados, es importante conocer los elementos traza del organismo.
    ! Los complejos multivitaminados, deben tomarse de 1 a 3 veces al ano, y con un maximo de 1 a 2 meses por vez.
    ! Existen 2 tipos de vitamina D, el ergocalciferol (vitamina D2) el colecalciferol (vitamina D3). La D3 se almacena mucho mejor en el cuerpo y a largo plazo. Ademas casi ningun alimento contiene vitamina D, y los que la contienen, es una cantidad minuscula en comparacion con la que se puede conseguir mediante la exposicion de la piel en los rayos ultravioleta.
    ! Hay otros nombres por los que se conocen algunas vitaminas: Vitamina B3=PP, K2=forma de almacenar en animales la vitamina K, F=nombre inicial para omega3, H=B7/B8,

  - Minerales: son elementos quimicos necesarios para la vida humana. Existen unos 20 esenciales y su carencia da lugar a alteraciones bioquímicas que son reversibles con el aporte del nutriente deficitario.
    * Macrominerales: son aquellos minerales que se necesitan en cantidades superiores a 100 mg/día.
      - Calcio: Además de su función en la construcción y mantenimiento de huesos y dientes, el calcio también tiene otras funciones metabólicas. Afecta la función de transporte de las membranas celulares, actuando como un estabilizador de la membrana. También influye en la transmisión de iones a través de las membranas, y la liberación de neurotransmisores. Este calcio actúa como mediador intracélular cumpliendo una función de segundo mensajero; por ejemplo, el ion Ca2+ interviene en la contracción de los músculos. También está implicado en la regulación de algunas enzimas quinasas que realizan funciones de fosforilación, por ejemplo la proteína quinasa C (PKC), y realiza unas funciones enzimáticas similares a las del magnesio en procesos de transferencia de fosfato (por ejemplo, la enzima fosfolipasa A2). Se requiere calcio en la trasmisión nerviosa y en la regulación de los latidos cardíacos. El equilibrio adecuado de los iones de calcio, sodio, potasio y magnesio mantiene el tono muscular y controla la irritabilidad nerviosa.
      - Fosforo: Forma parte de la molécula de Pi («fosfato inorgánico»), así como de las moléculas de ADN y ARN y de los fosfolípidos en las membranas lipídicas. Las células lo utilizan para almacenar y transportar la energía mediante el adenosín trifosfato. Además, la adición y eliminación de grupos fosfato a las proteínas, fosforilación y desfosforilación, respectivamente, es el mecanismo principal para regular la actividad de proteínas intracélulares, y de ese modo el metabolismo de las células eucariotas tales como los espermatozoides.
      - Magnesio: mantiene el equilibrio energético en las neuronas y actúa sobre la transmisión nerviosa, manteniendo al sistema nervioso en buena salud. Es utilizado como tratamiento antiestrés y antidepresión además de como relajante muscular. El magnesio ayuda a fijar el calcio y el fósforo en los huesos y dientes. Previene los cálculos renales ya que moviliza al calcio. Es también efectivo en las convulsiones del embarazo: previene los partos prematuros manteniendo al útero relajado. Interviene en el equilibrio hormonal, disminuyendo los dolores premenstruales. Actúa sobre el sistema neurológico favoreciendo el sueño y la relajación. Autorregula la composición y propiedades internas (homeostasis).     Actúa controlando la flora intestinal y nos protege de las enfermedades cardiovasculares. Favorable para quien padezca de hipertensión.
      - Sodio: Tiene un papel fundamental en el metabolismo celular, por ejemplo, en la transmisión del impulso nervioso (mediante el mecanismo de bomba de sodio-potasio). Mantiene el volumen y la osmolaridad. Participa, además del impulso nervioso, en la contracción muscular, el equilibrio ácido-base y la absorción de nutrientes por las membranas.
      - Potasio: Está involucrado en el mantenimiento del equilibrio normal del agua, el equilibrio osmótico entre las células y el fluido intersticial2 y el equilibrio ácido-base, determinado por el pH del organismo. El potasio también está involucrado en la contracción muscular y la regulación de la actividad neuromuscular, al participar en la transmisión del impulso nervioso a través de los potenciales de acción del organismo humano. Debido a la naturaleza de sus propiedades electrostáticas y químicas, los iones de potasio son más grandes que los iones de sodio, por lo que los canales iónicos y las bombas de las membranas celulares pueden distinguir entre los dos tipos de iones; bombear activamente o pasivamente permitiendo que uno de estos iones pase, mientras que bloquea al otro.3 El potasio promueve el desarrollo celular y en parte es almacenado a nivel muscular, por lo tanto, si el músculo está siendo formado (periodos de crecimiento y desarrollo) un adecuado abastecimiento de potasio es esencial.
      - Cloro: regula el equilibrio ácido-base del organismo por medio de distintos mecanismos: transporte de líquidos, intercambio de líquidos a través de la membrana celular (el cloro es el anion mientras que el Sodio es cation), etc. También ayudan en procesos de absorción, filtrado y transporte, mantenimiento del pH corporal y del pH renal.
      - Azufre: el azufre se encuentra presente en la queratina, que es una sustancia proteica de la piel, uñas y pelo, participa en la síntesis del colágeno (elemento que mantiene unidas a las células). También interviene en el metabolismo de los lípidos y de los hidratos de carbono.
    * Oligoelementos, microminerales o elementos traza: aquellos que sólo son precisan en muy pequeñas cantidades.
      - Hierro: Necesario no solo para lograr una adecuada oxigenación tisular sino también para el metabolismo de la mayor parte de las células. Los animales para transportar el hierro dentro del cuerpo emplean unas proteínas llamadas transferrinas. Para almacenarlo, emplean la ferritina y la hemosiderina.
      - Manganeso: tiene un papel tanto estructural como enzimático. Está presente en distintas enzimas, destacando la superóxido dismutasa de manganeso (Mn-SOD), que cataliza la dismutación de superóxidos, O2-; la Mn-catalasa, que cataliza la dismutación de peróxido de hidrógeno, H2O2; así como en la concavanila A (de la familia de las lectinas), en donde el manganeso tiene un papel estructural.
      - Cobre: contribuye a la formación de glóbulos rojos y al mantenimiento de los vasos sanguíneos, nervios, sistema inmunitario y huesos y por tanto es esencial para la vida humana.
      - Yodo: La glándula tiroides fabrica las hormonas tiroxina y triyodotironina, que contienen yodo. Las hormonas tiroideas juegan un papel muy básico en la biología, actuando sobre la transcripción genética para regular la tasa metabólica basal. La T4 actúa como un precursor de la T3, la cual es (con algunas excepciones menores) la hormona biológicamente activa, la acción de dichas hormonas es indispensable para el crecimiento y maduración del sistema nervioso central en la etapa prenatal y los primeros años de vida del ser humano, además de su crecimiento y desarrollo somático ulterior.
      - Zinc: interviene en el metabolismo de proteínas y ácidos nucleicos, estimula la actividad de aproximadamente 100 enzimas, colabora en el buen funcionamiento del sistema inmunitario, es necesario para la cicatrización de las heridas, interviene en las percepciones del gusto y el olfato y en la síntesis del ADN. El metal se encuentra en la insulina, las proteínas dedo de cinc (zinc finger) y diversas enzimas como la superóxido dismutasa. La mayoría del cinc se encuentra en el cerebro, los músculos, los huesos, el riñón y el hígado, con las concentraciones más altas en la próstata y las partes del ojo.9 El semen es particularmente rico en cinc, siendo un factor clave en la correcta función de la glándula prostática y en el crecimiento de los órganos reproductivos. El cinc aumenta la testosterona en sangre indirectamente, funcionando como coenzima en el metabolismo de las hormonas masculinas por medio de su formación a través de la hormona luteinizante (LH), que estimula las células de Leydig.11 12 También previene que la testosterona se degrade en estrógeno por medio de la enzima aromatasa. En el cerebro, el cinc se almacena en determinadas vesículas sinápticas mediante neuronas glutamatérgicas14 y puede "modular la excitabilidad del cerebro".15 Desempeña un papel clave en la plasticidad sináptica y por lo tanto en el aprendizaje.16 Sin embargo, ha sido llamado el "caballo oscuro del cerebro" (“the brain's dark horse”)14 ya que también puede comportarse como una neurotoxina, lo que sugiere que la adecuada homeostasis del cinc desempeña un papel fundamental en el funcionamiento normal del cerebro y del sistema nervioso central.
      - Cobalto: Una deficiencia de cobalto puede llevar a anemia. Las proteínas basadas en la cobalamina usan el anillo de corrina para mantener unido el cobalto. La coenzima B12 proporciona el enlace C-Co, el cual participa en las reacciones.
      - Fluor: Se localiza principalmente en los dientes y huesos, donde se incorpora a los cristales de hidroxiapatita, sustituye al ión hidrocxilo y da lugar a cristales de fluoropatita. Además de estos tejidos, el flúor se encuentra también en la piel, tiroides, plasma, linfa y vísceras. Es imprescindible en la prevención de las caries dentales ya que por un lado, refuerza la estructura mineral de los dientes y mantiene el esmalte y por otro, actúa sobre las bacterias cariogénicas inhibiendo su metabolismo y adhesión a la placa dental.
      - Selenio: Es antioxidante, ayuda a neutralizar los radicales libres, induce la apoptosis, estimula el sistema inmunológico e interviene en el funcionamiento de la glándula tiroides. Las investigaciones realizadas sugieren la existencia de una correlación entre el consumo de suplementos de selenio y la prevención del cáncer en humanos.
      - Cromo: o se conocen con exactitud sus funciones. Parece participar en el metabolismo de los lípidos, en el de los hidratos de carbono, así como otras funciones. Se ha observado que algunos de sus complejos parecen potenciar la acción de la insulina, por lo que se les ha denominado "factor de tolerancia a la glucosa"; debido a esta relación con la acción de la insulina, la ausencia de cromo provoca una intolerancia a la glucosa, y esta ausencia, la aparición de diversos problemas.
      - Molibdeno: En los animales y las plantas, estas enzimas usan el molibdeno como un cofactor. Todos los seres vivos que utilizan enzimas de molibdeno. Las enzimas de molibdeno en las plantas y animales catalizan la oxidación y la reducción a veces de ciertas moléculas pequeñas, como parte de la regulación de nitrógeno, azufre y los ciclos del carbono.
      - Niquel: Un 87% de las hidrogenasas contienen níquel, especialmente en aquellas cuya función es oxidar el hidrógeno. El níquel sufre cambios en su estado de oxidación lo que indica que el núcleo de níquel es la parte activa de la enzima. El níquel está también presente en la enzima metil con reductasa y en bacterias metanogénicas.
      - Vanadio: Existen compuestos de vanadio que imitan y potencian la actividad de la insulina. En humanos no está demostrada su esencialidad.
      - Estaño: Podría estar involucrado en la actividad de la gastrina que regula la producción de CLH del estómago. Sin embargo, hasta la fecha de la bibliografía consultada, no se ha demostrado su esencialidad en la especie humana.
      - Silicio*: El silicio entra en la estructura tisular del colágeno (proteína constituyente de muchos tejidos, entre ellos la piel), de la elastina y de las paredes arteriales: esto permite prevenir y evitar las esclerosis por calcificación de los tejidos, proteger la pared interna de las arterias y ayudar al mantenimiento de la elasticidad de la piel. El silicio permite, igualmente, la fijación del calcio y así previene el agotamiento de los huesos y las enfermedades óseas (osteoporosis).


*** Tables
 Current tables shows only for men from 31-50 years:

 Vitaminas:

 |--------+-------+------+-------+--------+--------+--------+-------+--------+--------+--------+------+-------+--------|
 | A      | C     | D    | E     | K      | B1     | B2     | B3    | B6     | B9     | B12    | B5   | B8    | B7     |
 |--------+-------+------+-------+--------+--------+--------+-------+--------+--------+--------+------+-------+--------|
 | 900 μg | 90 mg | 5 μg | 15 mg | 120 μg | 1,2 mg | 1,3 mg | 16 mg | 1,3 mg | 400 μg | 2,4 μg | 5 mg | 30 μg | 550 mg |
 |--------+-------+------+-------+--------+--------+--------+-------+--------+--------+--------+------+-------+--------|

  Vitamina A: Retinol
  Vitamina C: Ácido ascorbico
  Vitamina D: Calciferol
  Vitamina E: α-tocoferol
  Vitamina K: Fitomenadiona
  Vitamina B1: Tiamina
  Vitamina B2: Riboflavina
  Vitamina B3: Niacina
  Vitamina B5: Ácido Pantotenico
  Vitamina B6: Piridoxina, piridoxal y piridoxamina
  Vitamina B7: Colina
  Vitamina B8: Biotina
  Vitamina B9: Folato
  Vitamina B12: Cobalamina

 Minerales (oligoelementos):

 |---------+-------+--------+---------+--------+--------+----------+-----------+-----------+---------+---------+-------+---------+-------+---------|
 | Calcio  | Cromo | Cobre  | Floruro | Yodo   | Hierro | Magnesio | Manganeso | Molibdeno | Fosforo | Selenio | Cinc  | Potasio | Sodio | Cloruro |
 |---------+-------+--------+---------+--------+--------+----------+-----------+-----------+---------+---------+-------+---------+-------+---------|
 | 1000 mg | 35 μg | 900 μg | 4 mg    | 150 μg | 8 mg   | 420 mg   | 2,3 mg    | 45 μg     | 700 mg  | 55 μg   | 11 mg | 4,7 g   | 1,5 g | 2,3 g   |
 |---------+-------+--------+---------+--------+--------+----------+-----------+-----------+---------+---------+-------+---------+-------+---------|

 Energia:

 |------------------------------|
 | Consumo de energía           |
 |------------------------------|
 | 3067 - 10 kcal/dia > 19 años |
 |------------------------------|

 Macronutrientes:

 |------+-----------+---------------+-------+---------+-----------------------------------------------------+--------------------------------------------------------+----------------------------------------------|
 | Tipo | Proteinas | Carbohidratos | Fibra | Grasas  | Ácidos grasos poliinsaturados n-6 (ácido linoleico) | Ácidos grasos poliinsaturados n-3 (ácido α-linolenico) | Ácidos grasos saturados y trans y colesterol |
 |------+-----------+---------------+-------+---------+-----------------------------------------------------+--------------------------------------------------------+----------------------------------------------|
 | ADR  | 56 g      | 130 g         | 38 g  |         | 17 g                                                | 1,6 g                                                  |                                              |
 |------+-----------+---------------+-------+---------+-----------------------------------------------------+--------------------------------------------------------+----------------------------------------------|
 | IADM | 10-35 g   | 45-65 g       |       | 20-35 g | 5-10 g                                              | 0,6-1,2 g                                              |                                              |
 |------+-----------+---------------+-------+---------+-----------------------------------------------------+--------------------------------------------------------+----------------------------------------------|

  ADR (Aportes Diarios Recomendados)
  IADM (Intervalo Aceptable de Distribucion de Macronutrientes)

  Lista de aminoácidos necesarios para el cuerpo humano:

  |-----------------------+------------------+
  | Esenciales            | No esenciales    |
  |-----------------------+------------------+
  | Isoleucina (Ile)      | Alanina (Ala)    |
  |-----------------------+------------------+
  | Leucina (Leu)         | Tirosina (Tyr)   |
  |-----------------------+------------------+
  | Lisina (Lys)          | Aspartato (Asp)  |
  |-----------------------+------------------+
  | Metionina (Met)       | Cisteina (Cys)   |
  |-----------------------+------------------+
  | Fenilalanina (Phe)    | Glutamato (Glu)  |
  |-----------------------+------------------+
  | Treonina (Thr)        | Glutamina (Gln)  |
  |-----------------------+------------------+
  | Triptofano (Trp)      | Glicina (Gly)    |
  |-----------------------+------------------+
  | Valina (Val)          | Prolina (Pro)    |
  |-----------------------+------------------+
  | Hirstidina (His) cond | Serina (Ser)     |
  |-----------------------+------------------+
  | Arginina (Arg) cond   | Asparagina (Asn) |
  |-----------------------+------------------+

  Funciones de los aminoácidos esenciales:
  Isoleucina (Ile): La Isoleucina es necesaria para la formación de hemoglobina, estabiliza y regula el azúcar en la sangre y los niveles de energía. Este aminoácido es valioso para los deportistas porque ayuda a la curación y la reparación del tejido muscular, piel y huesos. La cantidad de este aminoácido se ha visto que es insuficiente en personas que sufren de ciertos trastornos mentales y físicos.
  Leucina (Leu): La leucina interactúa con los aminoácidos isoleucina y valina para promover la cicatrización del tejido muscular, la piel y los huesos y se recomienda para quienes se recuperan de la cirugía. Este aminoácido reduce los niveles de azúcar en la sangre y ayuda a aumentar la producción de la hormona del crecimiento.
  Lisina (Lys): Funciones de este aminoácido son garantizar la absorción adecuada de calcio y mantiene un equilibrio adecuado de nitrógeno en los adultos. Además, la lisina ayuda a formar colágeno que constituye el cartílago y tejido conectivo. La Lisina también ayuda a la producción de anticuerpos que tienen la capacidad para luchar contra el herpes labial y los brotes de herpes y reduce los niveles elevados de triglicéridos en suero.
  Metionina (Met): La Metionina es un antioxidante de gran alcance y una buena fuente de azufre, lo que evita trastornos del cabello, piel y uñas, ayuda a la descomposición de las grasas, ayudando así a prevenir la acumulación de grasa en el hígado y las arterias, que pueden obstruir el flujo sanguíneo a el cerebro, el corazón y los riñones, ayuda a desintoxicar los agentes nocivos como el plomo y otros metales pesados, ayuda a disminuir la debilidad muscular, previene el cabello quebradizo, protege contra los efectos de las radiaciones, es beneficioso para las mujeres que toman anticonceptivos orales, ya que promueve la excreción de los estrógenos, reduce el nivel de histamina en el cuerpo que puede causar que el cerebro transmita mensajes equivocados, por lo que es útil a las personas que sufren de esquizofrenia.
  Fenilalanina (Phe): Aminoácidos utilizados por el cerebro para producir la noradrenalina, una sustancia química que transmite señales entre las células nerviosas en el cerebro, promueve el estado de alerta y la vitalidad. La Fenilalanina eleva el estado de ánimo, disminuye el dolor, ayuda a la memoria y el aprendizaje, que se utiliza para tratar la artritis, depresión, calambres menstruales, las jaquecas, la obesidad, la enfermedad de Parkinson y la esquizofrenia.
  Treonina (Thr): La treonina es un aminoácido cuyas funciones son ayudar a mantener la cantidad adecuada de proteínas en el cuerpo, es importante para la formación de colágeno, elastina y esmalte de los dientes y ayuda a la función lipotrópica del hígado cuando se combina con ácido aspártico y la metionina, previene la acumulación de grasa en el hígado, su metabolismo y ayuda a su asimilación.
  Triptofano (Trp): Este aminoácido es un relajante natural, ayuda a aliviar el insomnio induciendo el sueño normal, reduce la ansiedad y la depresión y estabiliza el estado de ánimo, ayuda en el tratamiento de la migraña, ayuda a que el sistema inmunológico funcione correctamente. El Triptofano ayuda en el control de peso mediante la reducción de apetito, aumenta la liberación de hormonas de crecimiento y ayuda a controlar la hiperactividad en los niños.
  Valina (Val): La Valina es necesaria para el metabolismo muscular y la coordinación, la reparación de tejidos, y para el mantenimiento del equilibrio adecuado de nitrógeno en el cuerpo, que se utiliza como fuente de energía por el tejido muscular. Este aminoácido es útil en el tratamiento de enfermedades del hígado y la vesícula biliar, promueve el vigor mental y las emociones tranquilas.
  Hirstidina (His): Este aminoácido se encuentra abundantemente en la hemoglobina y se utiliza en el tratamiento de la artritis reumatoide, alergias, úlceras y anemia. Es esencial para el crecimiento y la reparación de los tejidos. La Histidina, también es importante para el mantenimiento de las vainas de mielina que protegen las células nerviosas, es necesario para la producción tanto de glóbulos rojos y blancos en la sangre, protege al organismo de los daños por radiación, reduce la presión arterial, ayuda en la eliminación de metales pesados del cuerpo y ayuda a mejorar la líbido.
  Arginina (Arg): Este aminoácido está considerado como "El Viagra Natural" por el aumento del flujo sanguíneo hacia el miembro viril, retrasa el crecimiento de los tumores y el cáncer mediante el refuerzo del sistema inmunológico, aumenta el tamaño y la actividad de la glándula del timo, que fabrica las células T, componentes cruciales del sistema inmunológico. La Arginina, ayuda en la desintoxicación del hígado neutralizando el amoniaco, reduce los efectos de toxicidad crónica de alcohol, que se utiliza en el tratamiento de la esterilidad en los hombres, aumentando el conteo de espermatozoides; ayudas en la pérdida de peso, ya que facilita un aumento de masa muscular y una reducción de grasa corporal, ayuda a la liberación de hormonas de crecimiento, que es crucial para el "crecimiento óptimo" músculo y la reparación de tejidos, es un componente importante del colágeno que es bueno para la artritis y trastornos del tejido conectivo y ayuda a estimular el páncreas para que libere insulina.

  Funciones de los aminoácidos no esenciales:
  Alanina (Ala): Desempeña un papel importante en la transferencia de nitrógeno de los tejidos periféricos hacia el hígado, ayuda en el metabolismo de la glucosa, un carbohidrato simple que el cuerpo utiliza como energía, protege contra la acumulación de sustancias tóxicas que se liberan en las células musculares cuando la proteína muscular descompone rápidamente para satisfacer las necesidades de energía, como lo que sucede con el ejercicio aeróbico, fortalece el sistema inmunológico mediante la producción de anticuerpos.
  Tirosina (Tyr): Es un aminoácido importante para el metabolismo general. La Tirosina es un precursor de la adrenalina y la dopamina, que regulan el estado de ánimo. Estimula el metabolismo y el sistema nervioso, actúa como un elevador del humor, suprime el apetito y ayuda a reducir la grasa corporal. La Tirosina ayuda en la producción de melanina (el pigmento responsable del color del pelo y la piel) y en las funciones de las glándulas suprarrenales, tiroides y la pituitaria, se ha utilizado para ayudar a la fatiga crónica, la narcolepsia, ansiedad, depresión, reducción de la líbido, alergias y dolores de cabeza.
  Aspartato (Asp): El Ácido Aspártico aumenta la resistencia y es bueno para la fatiga crónica y la depresión, rejuvenece la actividad celular, la formación de células y el metabolismo, que le da una apariencia más joven, protege el hígado, ayudando a la expulsión de amoniaco y se combina con otros aminoácidos para formar moléculas que absorben las toxinas y sacarlas de la circulación sanguínea. Este aminoácido también ayuda a facilitar la circulación de ciertos minerales a través de la mucosa intestinal, en la sangre y las células y ayuda a la función del ARN y ADN, que son portadores de información genética.
  Cisteina (Cys): La Cisteína funciona como un antioxidante de gran alcance en la desintoxicación de toxinas dañinas. Protege el cuerpo contra el daño por radiación, protege el hígado y el cerebro de daños causados por el alcohol, las drogas y compuestos tóxicos que se encuentran en el humo del cigarrillo, se ha utilizado para tratar la artritis reumatoide y el endurecimiento de las arterias. Otras funciones de este aminoácido es promover la recuperación de quemaduras graves y la cirugía, promover la quema de grasa y la formación de músculos y retrasar el proceso de envejecimiento. La piel y el cabello se componen entre el 10% y el 14% de este aminoácido.
  Glutamato (Glu): El Ácido Glutámico actúa como un neurotransmisor excitatorio del sistema nervioso central, el cerebro y la médula espinal. Es un aminoácido importante en el metabolismo de azúcares y grasas, ayuda en el transporte de potasio en el líquido cefalorraquídeo, actúa como combustible para el cerebro, ayuda a corregir los trastornos de personalidad, y es utilizado en el tratamiento de la epilepsia, retraso mental, distrofia muscular y úlceras.
  Glutamina (Gln): Es el aminoácido más abundante en los músculos. La Glutamina ayuda a construir y mantener el tejido muscular, ayuda a prevenir el desgaste muscular que puede acompañar a reposo prolongado en cama o enfermedades como el cáncer y el SIDA. Este aminoácido es un "combustible de cerebros" que aumenta la función cerebral y la actividad mental, ayuda a mantener el equilibrio del ácido alcalino en el cuerpo, promueve un sistema digestivo saludable, reduce el tiempo de curación de las úlceras y alivia la fatiga, la depresión y la impotencia, disminuye los antojos de azúcar y el deseo por el alcohol y ha sido usado recientemente en el tratamiento de la esquizofrenia y la demencia.
  Glicina (Gly): La Glicina retarda la degeneración muscular, mejora el almacenamiento de glucógeno, liberando así a la glucosa para las necesidades de energía, promueve una próstata sana, el sistema nervioso central y el sistema inmunológico. Es un aminoácido útil para reparar tejidos dañados, ayudando a su curación.
  Prolina (Pro):Funciones de este aminoácido son mejorar la textura de la piel, ayudando a la producción de colágeno y reducir la pérdida de colágeno a través del proceso de envejecimiento. Además, la Prolina ayuda en la cicatrización del cartílago y el fortalecimiento de las articulaciones, los tendones y los músculos del corazón. La Prolina trabaja con la vitamina C para ayudar a mantener sanos los tejidos conectivos.
  Serina (Ser): Este aminoácido es necesario para el correcto metabolismo de las grasas y ácidos grasos, el crecimiento del músculo, y el mantenimiento de un sistema inmunológico saludable. La Serina es un aminoácido que forma parte de las vainas de mielina protectora que cubre las fibras nerviosas, es importante para el funcionamiento del ARN y ADN y la formación de células y ayuda a la producción de inmunoglobulinas y anticuerpos.
  Asparagina (Asn): Es creada en el cuerpo por el hígado y se utiliza fundamentalmente para alimentar el sistema nervioso. La glicosilación de la asparigina es un fenómeno muy importante que sufren las proteínas destinadas al espacio extracélular. El ácido ayuda al sistema nervioso a mantener el equilibrio emocional, éste se utiliza para la prevención del desarrollo a un alto grado de sensibilidad al sonido y al tacto.

  Aminoácidos en productos (según PDCAAS - Protein Digestibility Corrected Amino Acids Score desarrollado por la FDA para mejorar el PER (Protein Efficiency Ratio)). Existen otros metodos como VB, NPU, PER, NB o PD:

  |--------+-----------------------|
  | PDCAAS | Producto              |
  |--------+-----------------------|
  |   1.00 | casein (milk protein) |
  |--------+-----------------------|
  |   1.00 | egg white             |
  |--------+-----------------------|
  |   1.00 | soy protein           |
  |--------+-----------------------|
  |   1.00 | whey (milk protein)   |
  |--------+-----------------------|
  |   0.99 | mycoprotein           |
  |--------+-----------------------|
  |   0.92 | beef                  |
  |--------+-----------------------|
  |   0.78 | chickpeas             |
  |--------+-----------------------|
  |   0.76 | fruits                |
  |--------+-----------------------|
  |   0.75 | black beans           |
  |--------+-----------------------|
  |   0.73 | vegetables            |
  |--------+-----------------------|
  |   0.70 | other legumes         |
  |--------+-----------------------|
  |   0.64 | yellow split pea      |
  |--------+-----------------------|
  |   0.59 | cereals               |
  |--------+-----------------------|
  |   0.52 | peanuts               |
  |--------+-----------------------|
  |   0.42 | whole wheat           |
  |--------+-----------------------|
  |   0.25 | wheat gluten (food)   |
  |--------+-----------------------|

  Organizacion de aminoácidos para eleccion de alimentos según la variedad de los mismos y tipo:

  Cuando consideramos que eleccion de alimentos debemos obtener para la ingesta de aminoácidos debemos dividirlos en 4 categorias:

  |-----------------------------------+-------------------------------------+---------------------+--------------------------------|
  | BCAAs (Branched-chain aminoacids) | SAAs (Sulfur-containing aminoacids) | Aromatic aminoacids | Other indispensable aminoacids |
  |-----------------------------------+-------------------------------------+---------------------+--------------------------------|
  | Isoleucine                        | Methionine                          | Histidine           | Lysine                         |
  | Leucine                           | Cysteine*                           | Phenylalanine       | Threonine                      |
  | Valine                            |                                     | Tyrosine            |                                |
  |                                   |                                     | Tryptophan          |                                |
  |-----------------------------------+-------------------------------------+---------------------+--------------------------------|

  Alimentos con alta concentracion de BCAAs (requerira la ingesta de 7 a 50 gr):
   * Pescado
   * Huevos
   * Productos derivados de animales y lácteos (queso, leche, etc)
   * Vegetales marinos (algas)
   * Soja y derivados de la soja
   E.g.: 226 gr de tofu, bacalao o gambas. Un yogurt o 28 gr de queso proveera entre el 25% y el 33% de esta cantidad.
  Alimentos con alta concentracion de SAAs (combinando methionine+cysteina o methionina solo ya que esta ultima puede convertirse en cisteina por el cuerpo):
   * Salmon
   * Legumbres
   * Frutos secos
   * Semillas
   * Vegetales (especialmente ajo, cebolla, puerro, o brocoli, col y similares).
   E.g.: 112 gr de salmon o 2 tazas de la mayoria de legumbres o 224 gr de frutos secos o semillas.
  Alimentos con alta concentracion de aminoácidos aromaticos:
   * Frutos secos
   * Semillas
   * Vegetales
   * Huevos
   * Productos derivados de animales y lácteos (queso, leche, etc)
   * Tofu
   * Salmon
   * Pollo
   E.g.: Para el triptofano 56 gr de frutos secos o semillas, entre 112 y 168 gr de vegetales, 5 yogures, 2 huevos o 70 gr de queso o 75 gr de salmon o 56 gr de pollo.
   E.g.: Para el phenylalanine es mas complejo: 224 gr de la mayoria de pescados y carnes, 84 gramos de la mayoria de legumbres o tofu, 168 gr de la mayoria de frutos secos o semillas. Los vegetales solo contienen un 5% por plato de la cantidad necesaria.
  Alimentos con alta concentracion de otros aminoácidos indispensables:
   * Legumbres
   * Frutos secos
   * Tofu
   * Huevos
   * Productos derivados de animales y lácteos (queso, leche, etc)
   E.g.: 2 tazas de legumbres, 140 gr de frutos secos, 168 gr de tofu, 4 huevos o 112 gr de queso, 3 yogures, 112 gr de pescado o pollo.

   Productos vegetarianos recomendados para todos los aminoácidos: judias, lentejas, guisantes, tofu, tempeh y otras legumbres. Asi como frutos secos, semillas, vegetales (especialmente por las vitaminas y minerales, pero cuando se toman en grandes cantidades se pueden obtener gran cantidad de aminoácidos). Las frutas, no son determinantes a la hora de adquirir aminoácidos, por ello no fueron incluidos en estas listas (por racion tan solo proveen entre el 1% y el 3% necesario).

   Ingesta necesaria de aminoácidos por dia:

   Miligramos por kg de peso
   |---------------------------+------------+---------+--------+---------------------+-----------------------+-----------+------------+--------|
   | Histidine                 | Isoleucine | Leucine | Lysine | Methionine+Cysteine | Phenlalanine+Tyrosine | Threonine | Tryptophan | Valine |
   |---------------------------+------------+---------+--------+---------------------+-----------------------+-----------+------------+--------|
   | 14                        |         19 |      42 |     38 |                  19 |                    33 |        20 |          5 |     24 |
   |---------------------------+------------+---------+--------+---------------------+-----------------------+-----------+------------+--------|
   Miligramos para una persona de 75 kg de peso
   |-----------+------------+---------+---------+---------------------+-----------------------+-----------+------------+---------|
   | Histidine | Isoleucine | Leucine | Lysine  | Methionine+Cysteine | Phenlalanine+Tyrosine | Threonine | Tryptophan | Valine  |
   |-----------+------------+---------+---------+---------------------+-----------------------+-----------+------------+---------|
   | 1050      | 1425       | 3150    | 2850    | 1425                | 2475                  | 1500      | 375        | 1800    |
   | (~1 gr)   | (~1.5 gr)  | (~3 gr) | (~3 gr) | (~1.5 gr)           | (~2.5 gr)             | (~1.5 gr) | (~0.5 gr)  | (~2 gr) |
   |-----------+------------+---------+---------+---------------------+-----------------------+-----------+------------+---------|


*** Digestion, absorción, transporte y excrecion de nutrientes
**** Aparato digestivo

 Funciones del tubo digestivo:
  - Extraer macronuetrientes, proteínas, carbohidratos, lípidos, agua y etanol de los alimentos ingeridos.
  - Absorber micronutrientes y oligoelementos necesarios.
  - Actuar como barrera fisica e inmunitaria frente a microorganismos, materiales extranos y posibles antigenos.

 Es capaz de absorber entre el 90 y 97% de los alimentos pero es poco eficiente en la extraccion de energía de hierbas, tallos, semillas y otros materiales fibrosos porque carecen de enzimas que hidrolizan los enlaces quimicos que unen entre sí moléculas de azucares que forman las fibras vegetales.

 El intestino esta configurado con un patron de pliegues, fosas y proyecciones digitiformes denominadas vellosidades.

 Las células que recubren el tubo digestivo tienen una vida de 3-5 dias y despues son recicladas. Estas células son completamente funcionales los ultimos 2-3 dias.

 La función optima del tubo digestivo humano parece depender mas de un aporte constante de alimentos que del consumo de grandes cantidades de alimentos intercalado con ayunos prolongados.

**** Proceso de digestión y absorción

 - La masticacion reduce el tamaño de las particulas, mezcladas con las secreciones salivares que las preparan para la deglucion.
 - Una pequena cantidad de almidon es degradada por la amilasa salival.
 - En el estomago el alimento se mezcla con el líquido ácido y las enzimas proteoliticas y lipoliticas, produciendo pequenas cantidades de digestión de lípidos y algunas proteínas cambian de estructura o son digeridas para dar péptidos grandes.
 - En el intestino delgado se produce la digestión, absorbiendo la mayor parte del alimento ingerido. La presencia de alimento aqui produce liberación de hormonas, estimulando la sintesis y la liberación de potentes enzimas desde el pancreas y el intestino delgado y de bilis desde el hígado y la vesicula biliar. Asi se reducen almidones y proteínas hasta carbohidratos de menor peso molecular y péptidos de menor tamaño.
 - Las grasas se reducen desde globulos de grasa visibles hasta gotas microscopicas de triglicéridos y mas tarde hasta ácidos grasos libres y monoglicéridos.
 - Las enzimas del borde en cepillo del intestino delgado reducen aun mas los carbohidratos a monosacáridos y los péptidos a aminoácidos unicos, dipéptidos y tripéptidos.
 - Secreciones salivares, gastricas y secreciones del pancreas el intestino delgado y la vesicula biliar contribuyen con 7-9L de líquido al dia.
 - El movimiento del material ingerido y secretado esta regulado principalmente por hormonas peptídicas, nervios y musculos entericos.
 - A lo largo del restante intestino delgado se absorben casi todos los macronutrientes, minerales, vitaminas, oligoelementos y líquido antes de llegar al intestino grueso (colon).
 - El colon y el recto absorben la mayor parte de líquidos restantes. Absorben electrolitos y pequenas cantidades de nutrientes restantes.
 - La mayoria de nutrientes absorbidos por el tubo digestivo se dirige hacia el hígado a través de la vena porta, donde se pueden almancenar, transformar en otras sustancias o ser liberados hacia la circulación.
 - Los productos terminales de la mayor parte de las grasas se transportan en ultimo termino hacia el torrente sanguineo a través de la circulación linfatica.
 - La flora colonica tiene la función de fermentar de parte de la fibra restante, el almidon resistente, los azucares y los aminoácidos.
 - La fermentacion de los carbohidratos restantes da lugar a la sintesis de Ácidos Grasos de Cadena Corta (AGCC) y gas.
 - Los AGCC ayudan a mantener la función normal de la mucosa y rescatan una pequena cantidad de energía de los sustratos residuales y facilitan la absorción del resto de la sal y el agua.
 - Los sustratos restantes, especialmente fibras elementales, actúan como material prebiotico sintatizando AGCC, reduciendo el pH colonico y aumentando la masa de bacterias utiles.

 La digestión del alimento se consigue por la hidrolisis dirigida por las enzimas. El ácido clorhidrico, la bilis y el bicarbonato socido favorecen los procesos de digestión y absorción

 El movimiento del tubo digestivo incluye contraccion, mezclado y propulsion del contenido luminal como resultado de la actividad coordinada de los nervios entericos, nervios extrinsecos, células endocrinas y el musculo liso.

 Los neurotransmisores y los neuropéptidos con pesos moléculares pequenos envian senales a los nervios para que contraigan o relajen los musculos, aumenten o reduzcan las secreciones de líquidos o modifiquen el flujo sanguineo. De esta forma el tubo digestivo regula en gran medida su propia motilidad y actividad secretora.

Digestion enzimatica en la absorción:

|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
| Secrecion y origen                       | Enzimas                                      | Sustrato                    | Accion y productos resultantes                  | Productos finales absorbidos                 |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
| Saliva de las glandulas salivares        | Ptialina                                     | Almidon                     | Hidrolisis para formar dextrinas                | -                                            |
|                                          |                                              |                             | y oligosacáridos ramificados                    |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
| Jugo gastrico de las glandulas gastricas | Pepsina                                      | Proteinas                   | Hidrolisis de los enlaces peptidicos            | -                                            |
| de la mucosa del estomago                |                                              |                             | para formar polipéptidos y aminoácidos          |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Lipasa gastrica                              | Grasa de cadena corta       | Hidrolisis para formar ácidos grasos            | -                                            |
|                                          |                                              |                             | libres                                          |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
| Secreciones exocrinas del pancreas       | Lipasa                                       | Grasa                       | Hidrolisis para formar monoglicéridos y         | Ácidos grasos hacia las células de la mucosa |
|                                          |                                              |                             | ácidos grasos, incorporandose a las micelas     | reesterificandose como triglicéridos         |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Colesterol esterasa                          | Colesterol                  | Hidrolisis para formar esteres de colesterol    | Colesterol hacia las células de la mucosa;   |
|                                          |                                              |                             | y ácidos grasos incorporandose a las micelas    | se transfiere a los quilomicrones            |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | α-amilasa                                    | Almidon y dextrinas         | Hidrolisis para formar dextrinas y maltosa      | -                                            |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Tripsina                                     | Proteinas y polipéptidos    | Hidrolisis de los enlaces peptidicos internos   | -                                            |
|                                          | (tripsinogeno activado)                      |                             | para formar polipéptidos                        |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Quimotripsina                                | Proteinas y péptidos        | Hidrolisis de los enlaces peptidicos internos   | -                                            |
|                                          | (quimotripsinogeno activado)                 |                             | para formar polipéptidos                        |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Carboxipeptidasa                             | Polipéptidos                | Hidrolisis de los enlaces peptidicos terminales | Aminoácidos                                  |
|                                          |                                              |                             | (extremo carboxilico) para formar aminoácidos   |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Ribonucleasa y desoxirribonucleasa           | Ácidos ribonucleicos y      | Hidrolisis para formar mononucleotidos          | Mononucleotidos                              |
|                                          |                                              | ácidos desoxirribonucleicos |                                                 |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Elatasa                                      | Proteina fibrosa            | Hidrolisis para formar péptidos y aminoácidos   | -                                            |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
| Enzimas del intestino delgado            | Carboxipeptidasa, aminopeptidasa y peptidasa | Polipéptidos                | Hidrolisis de los enlaces péptidos de los       | Aminoácidos                                  |
|                                          |                                              |                             | extremos carboxilico o amino o internos         |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Enterocinasa                                 | Tripsinogeno                | Activa la tripsina                              | Dipéptidos y tripéptidos                     |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Sacarasa                                     | Sacarosa                    | Hidrolisis para formar glucosa y fructosa       | Glucosa y fructosa                           |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | α-dextrinasa (isomaltasa)                    | Dextrina (isomaltosa)       | Hidrolisis para formar glucosa                  | Glucosa                                      |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Maltasa                                      | Maltosa                     | Hidrolisis para formar glucosa                  | Glucosa                                      |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Lactasa                                      | Lactosa                     | Hidrolisis para formar glucosa y galactosa      | Glucosa y galactosa                          |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Nucleotidasas                                | Ácidos nucleicos            | Hidrolisis para formar nucleotidos y fosfatos   | Nucleotidos                                  |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|
|                                          | Nucleotidasa y fosforilasa                   | Nucleosidos                 | Hidrolisis para formar purinas, pirimidinas     | Bases purinicas y pirimidinicas              |
|                                          |                                              |                             | y pentosa fosfato                               |                                              |
|------------------------------------------+----------------------------------------------+-----------------------------+-------------------------------------------------+----------------------------------------------|

Neurotransmisores y sus acciones:

|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Neurotransmisor              | Punto de liberación                                                | Acciones principales                                                                        |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Ácido α-aminobutirico (GABA) | Sistema nervioso central                                           | Relaja el esfinter esofagico inferior                                                       |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Noradrenalina                | Sistema nervioso central, medula espinal, nervios simpaticos       | Reduce la motilidad, aumenta la contraccion de los esfinteres, inhibe las secreciones       |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Acetilcolina                 | Sistema nervioso central, sistema nervioso autonomo, otros tejidos | Aumenta la motilidad, relaja los esfinteres, estimula la secrecion                          |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Neurotensina                 | Tubo digestivo, sistema nervioso central                           | Inhibe la liberación del vaciado gastrico y la secrecion de ácido                           |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Serotonina (5-HT)            | Tubo digestivo, medula espinal                                     | Facilita la secrecion y el peritaltismo                                                     |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Oxido nitrico                | Sistema nervioso central, tubo digestivo                           | Regula el flujo sanguineo, mantiene el tono muscular, mantiene la actividad motora gastrica |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|
| Sustancia P                  | Intestino, sistema nervioso central, piel                          | Aumenta la conciencia sensitiva (principalmente dolor) y el peritaltismo                    |
|------------------------------+--------------------------------------------------------------------+---------------------------------------------------------------------------------------------|

Hormonas neuropeptídicas:

La regulacion del aparato digestivo implica a numerosas hormonas que pueden actuar localmente (con mecanismo autocrino o paracrino) o a distancia (endocrino). Existen mas de 100 hormonas peptídicas secretados por mas de 30 células diferentes neuroendodrinas, actuando algunas de ellas como neurotransmisores entre neuronas. Afectan al crecimiento, sintesis de ADN, proliferacion, secrecion, movimiento o metabolismo de las células del tubo digestivo.

 - Gastrina: es una hormona que estimula las secreciones y la motilidad del estomago. Es secretada principalmente por las células G endocrinas de la mucosa antral del estomago.
   secrecion: iniciada por distension del antro despues de una comida, impulsos procedentes del nervio vago (como los que se desencadenan por el olor o vista de alimentos), o por la presencia de en el antro de secretagogos como proteínas digeridas parcialmente, bebidas alcoholicas fermentadas, cafeina o extractos de alimentos. Cuando la luz se hace mas acida, la retroalimentacion en la que participan otras hormonas inhibe la liberación de gastrina. La gastrina se une a receptores de las células parietales y las células liberadores de histamina para estimular el ácido gastrico, a receptores de las células principales para liberar pepsinogeno y a receptores del musculo liso para aumentar la motolidad gastrica.

 - Secretina: es liberada por las células S de la pared intestinal del intestino delgado proximal hacia el torrente sanguineo.
   secrecion: en respuesta al ácido gastrico y a los productos finales de la digestión en el duodeno. Estimula al pancreas para que secrete agua y bicarbonato hacia el duodeno e inhibe la secrecion gastrica de ácido y el vaciado gastrico. La neutralizacion de la acidez protege a la mucosa duodenal de la exposicion prolongada al ácido y proporciona el entorno adecuado para la actividad de las enzimas intestinales y pancreaticas. El receptor es un receptor acoplado a la proteína G con siete dominios transmembranarios y se encuentra en el estomago y en las células ductales y acinares del pancreas.

 - Colecistocinina (CCK): es un importante hormona multifuncional, entre sus funciones se encuentran: estimular al pancreas para que secrete enzimas (y en menor medida bicarbonato y agua), estimular la contraccion de la vesicula biliar, estimular la motilidad colonica y rectal, y aumentar la saciedad.
   secrecion: células I de la mucosa del intestino delgado la secretan en respuesta ante la presencia de proteínas y grasas. Habiendo receptores de la CCK en las células acinares pancreaticas, en las células de los islotes pancreaticos, en las células D gastricas liberadoras de la somatostanina, en las células musculares lisas del tubo digestivo y en el sistema nervioso central.

 - Peptido similar al glucagon-1 (GLP-1) y el polipéptido insulinotropico dependiente de glucosa (GIP): estimulan la sintesis y la liberación de insulina. El GPL-1 también reduce la secrecion de glucagon, retrasa el vaciado gastrico y puede ayudar a favorecer la saciedad. El GPL-1 y el GIP son hormonas incretinas, que contribuyen a evitar que la glucosa sanguínea aumente excesivamente despues de una comida.
   secrecion: liberados por la mucosa intestinal en presencia de comidas ricas en glucosa y grasa

 - Motilina: liberada hacia el duodeno por las células de la parte proximal del intestino delgado. Aumenta la velocidad del vaciado gastrico y estimula la motilidad del tubo digestivo. Actua sobre sobre receptores acoplados a la proteína G de las neuronas entericas del duodeno y del colon y estimula la contraccion del musculo liso del estomago.
   secrecion: en respuesta a la bilis y a las secreciones pancreaticas.

 - Somatostatina: Es una hormona con acciones de gran alcance, siendo sus funciones inhibidoras y antisecretoras. Reduce la motilidad del estomago y del intestino e inhibe o regula la liberación de varias hormonas digestivas
   secrecion: liberada por las células D del antro y del piloro.

Funciones de las principales hormonas digestivas:

|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| Hormona               | Lugar de liberación                  | Estimulantes de la liberación                                                                      | Organo afectado                     | Efecto sobre el organo                                                                                                                                  |
|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| Gastrina              | Mucosa gastrica, duodeno             | péptidos, aminoácidos, cafeina, distension del antro. Bebidas alcoholicas fermentadas, nervio vago | Estomago, esofago, tubo digestivo.  | Estimula la secrecion del ácido clorhidrico (HCI) y pepsinogeno. Aumenta la motilidad antral gastrica. Aumenta el tono del esfinter esofagico inferior. |
|                       |                                      |                                                                                                    | Vesicula biliar.                    | Estimula debilmente la contraccion de la vesicula biliar.                                                                                               |
|                       |                                      |                                                                                                    | Pancreas.                           | Estimula debilmente la secrecion pancreatica de bicarbonato.                                                                                            |
|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| Secretina             | Mucosa duodenal                      | Ácido en el intestino delgado                                                                      | Pancreas.                           | Aumenta la liberación de H2O y bicarbonato. Aumenta la secrecion de algunas enzimas por el pancreas y la liberación de insulina.                        |
|                       |                                      |                                                                                                    | Duodeno.                            | Reduce la motilidad.                                                                                                                                    |
|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| Colecistocinina (CCK) | Intestino delgado proximal           | Peptidos, aminoácidos, grasas, HCI                                                                 | Pancreas.                           | Estimula la secrecion de enzimas pancreaticas.                                                                                                          |
|                       |                                      |                                                                                                    | Vesicula biliar.                    | Produce contraccion de la vesicula biliar.                                                                                                              |
|                       |                                      |                                                                                                    | Estomago.                           | Retrasa el vaciado gastrico.                                                                                                                            |
|                       |                                      |                                                                                                    | Colon.                              | Aumenta la motilidad. Puede mediar la conducta alimentaria.                                                                                             |
|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| GIP                   | Intestino delgado                    | Glucosa, grasa                                                                                     | Estomago, pancreas.                 | Estimula la liberación de la insulina.                                                                                                                  |
|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| GLP-1                 | Intestino delgado                    | Glucosa, grasa                                                                                     | Estomago, pancreas.                 | Prolonga el vaciado gastrico. Inhibe la liberación del glucagon. Estimula la liberación de la insulina                                                  |
|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| Motilina              | Estomago, intestino delgado y grueso | Secreciones biliares y pancreaticas                                                                | Estomago, intestino delgado, color. | Estimula el vaciado gastrico y la motilidad digestiva.                                                                                                  |
|-----------------------+--------------------------------------+----------------------------------------------------------------------------------------------------+-------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------|

Digestion en la boca: Los dientes muelen y trituran el alimento. Al mismo tiempo la masa es humedecida y lubricada por la saliva. 3 pares de glandulas salivares (parotidas, submandibulares y sublinguales) producen 1.5 L de saliva al dia. Una secrecion serosa que contiene amilasa (ptialina) comienza la digestión del almidon. La amilasa se inactiva cuando llega al contenido ácido del estomago. Otro tipo de saliva contiene moco, una proteína que hace que las particulas de alimento se ahdieran entre sí y lubrica la masa para su deglucion. Las secreciones orofaringeas también contienen una lipasa, que es capaz de digerir algunas grasas. La masa de alimento masticada pasa entonces a la zona posterior de la faringe bajo control voluntario, pero en todo el esofago el proceso de deglucion es involuntario. Despues el peritaltismo mueve el alimento hacia el estomago.

Digestion en el estomago: Los alimentos son propulsados en direccion retrogada y se mezclan con las secreciones gastricas por contracciones ondulatorias hacia adelante desde la porcion superior del estomago (fondo) hasta la porcion media (cuerpo) y posteriormente hasta el antro y el piloro. En el estomago las secreciones gastricas se mezclan con los alimentos y las bebidas. Las secreciones gastricas contienen ácido clorhidrico (secretado por las células parietales de las paredes del fondo y del cuerpo), una proteasa, la lipasa gastrica, moco, factor intrinseco (una glucoproteína que facilita la absorción de la vitamina B12 en el ileon). y la hormona digestiva gastrina. La proteasa es pepsina y es secretada por las glandulas del fondo y del cuerpo, primero en forma inactiva, pepsinogeno, que por el ácido clorhidrico se convierte en forma activa. La pepsina modifica tamaño y forma de algunas de las proteínas de una comida normal. Una lipasa estable en el medio ácido es secretada hacia el estomago por las células principales y contribuye al procesado global de los triglicéridos. En el proceso de la digestión gastrica la mayor parte del alimento se convierte en quimo semilíquido, conteniendo un 50% de agua aprox. Las secreciones gastricas son importantes para aumentar la disponibilidad y absorción distal de vitamina B12 y algunos metales y oligoelementos como calcio, hierro y cinc. El ácido del estomago es PH 1 a 4, que combinado con las enzimas proteoliticas del estomago dan lugar a una reudccion de microorganismos ingeridos. El estomago mezcla y agita continuamente el alimento, con cada contraccion del piloro y del antro, vaciandose la comida liquida en 1-2 horas y la solida en 2-3 horas. Los carbohidratos son los primeros que salen del estomago, seguidos por las proteínas, grasas y alimentos con fibra. Aunque en comidas mixtas este orden depende del volumen global y caracteristicas de los alimentos. Los líquidos se vacian antes que los solidos, las particulas pequenas antes que las grandes, el alimento diluido antes que el concentrado en calorias, El esfinter esofagico inferior, impide el flujo del contenido gastrico hacia el esofago, y el esfinter pilorico de la porcion distal del estomago ayuda a regular la salida del contenido gastrico e impide el flujo retrogrado del quimo desde el duodeno hacia el estomago.

Digestion en el intestino delgado: es el principal punto de digestión de los alimentos y nutrientes. Se divide en duodeno, yeyuno e ileon. El quimo ácido procedente del estomago entra en el duodeno, mezclandose con los jugos duodenales y con las secreciones del pancreas y del sistema biliar. Como consecuencia de la secrecion del líquido que contiene bicarbonato desde el pancreas y la dilucion por las demas secreciones, se neutraliza el quimo ácido. La entrada de alimentos digeridos parcialmente, pricipalmente grasas y proteínas, estimula la liberación de diversas hormonas que a su vez estimulan la secrecion de enzimas y líquidos y afectan a la motilidad digestiva y a la saciedad. La bilis, que es principalmente una mezcla de agua, sales biliares y cantidades pequenas de pigmentos y colesterol, es secretada desde el hígado y la vesicula biliar. Gracias a sus propiedades tensioactivas, las sales biliares facilitan la digestión y absorción de los lípidos. El pancreas secreta protentes enzimas (lipasa pancreatica y colipasa) capaces de digerir todos los nutrientes principales, y las enzimas del intestino delgado contribuyen a finalizar el proceso. Las enzimas proteoliticas, incluyen tripsina, quimotripsina, carboxipeptidasa, aminopeptidasa, ribonucleasa y desoxirribonucleasa. La tripsina y la quimotripsina son secretadas en sus formas inactivas y se activan por la enterocinasa (o enteropeptidasa), que se secreta cuando el quimo entra en contacto con la mucosa intestinal. La amilasa pancreatica tiene como función hidrolizar las grandes moléculas de almidon finalmente hasta unidades aproximadamente dos a seis azucares. Las enzimas que recubren el borde en cepillo de las vellosidades producen una hidrolisis adicional de las moléculas de carbohidratos para dar lugar a monosacáridos antes de su absorción. Una cantidad variable de almidones resistentes y la mayor parte de la fibra de la dieta ingerida escapan a la digestión en el intestino delgado y pueden contribuir al material fibroso disponible para la fermentacion por los microorganismos colonicos. El contenido intestinal avanza a 1 cm por minuto tardando de 3 a 8 horas en recorrer todo el intestino delgado hasta la valcula ileocecal, mientras que a lo largo del trayecto los sustratos restantes siguen siendo digeridos y absorbidos. La valvula ileocecal, como la valcula pilorica, sirve para limitar el paso de material intestinal en ambos sentidos entre en intestino delgado y el colon.


**** Intestino delgado

El intestino delgado tiene pliegues en su superficie llamados valvulas conniventes, que están recubiertas de microvellosidades o borde de cepillo. Las vellosidades descansan sobre una estructura de soporte llamada lamina propia, que esta formada por tejido conjuntivo, sangre y vasos linfaticos. Dentro de la lamina propia se reciben los productos de la digestión, absorbiendo 150-300 gr de monosacáridos, 60-100 gr de ácidos grasos, 60-120 gr de aminoácidos y péptidos, y 50-100 gr de iones de promedio. Sobre el 95% de las sales biliares secretadas por el hígado y por la vesicula biliar son reabsorbidas en forma de ácidos biliares en el ileon distal. El ileon distal también es el punto de absorción de la vitamina B12 con el factor intrinseco.

La emulsificacion de las grasas en el intestino delgado es seguida por su digestión, principalmente por la lipasa pancreatica para dar ácidos grasos libres y Beta-monoglicéridos. La lipasa pancreatica tipicamente escinde el primer y el tercer ácido graso, dejando uno unido al carbono medio del glicerol. Cuando la concentracion de sales biliares alcanza un nivel determinado, se forman micelas (complejos de ácidos grasos libres, monoglicéridos y sales biliares), que se organizan con los extremos polares de las moléculas orientados hacia la luz acuosa del intestino. Los productos de la digestión lipidica se solubilizan rápidamente en la procion central de las micelas y son transportados hacia la zona del borde en cepillo.

En la superficie del CAE (Capa Acuosa Estatica), que es la placa ligeramente acida y acuosa que forma el limite entre la luz intestinal y las membranas del borde del cepillo, los lípidos se separan en micelas, y los restos de las micelas vuelven a la luz por un transporte posterior. Dejando así los monoglicéridos y los ácidos grasos sigan su trayecto a través de la CAE lipofoba hacia las membranas celulares mas lipofilas del borde del cepillo. Cuando llegan, son captadas rápidamente para su procesado y su entrada en el sistema de transporte. La absorción de colesterol se puede realizar mediante transferencia pasiva y facilitada, que implica a un sistema de proteína transportadora especifica del colesterol y no de otros esteroles.

La absorción es un proceso muy complejo, que combina el proceso mas intrincado de transporte activo y de difusión pasiva, en el cual los nutrientes atraviesan las células de la mucosa intestinal (enterocitos o colonocitos) y finalmente se dirigen hacia la circulación linfatica o por el sistema venoso hacia el hígado. La difusión supone el movimiento aleatorio a través de aberturas de las membranas de las paredes de las células mucosas o entre las mismas utilizando proteínas de canales (difusión simple) o proteínas transportadoras (transporte), como una forma de difusión facilitada.

El transporte activo supone la aportacion de energía para desplazar los iones y otras sustancias, en combinacion con una proteína transportadora, a través de una membrana contra un gradiente de energía. Algunos nutrientes pueden compartir el mismo transportador y por tanto computen por su absorción. Los sistemas de transporte también se pueden saturar retrasando la absorción del nutriente. Un ejemplo de un transportador de este tipo es el factor intrinseco.

Algunas moléculas se desplazan desde la luz intestinal hacia las células mucosas por medio de bombas, que precisan un transportador y energía procedente del trifosfato de adenosina. La absorción de la glucosa, sodio, galactosa, potasio, magnesio, fosfato, yoduro, calcio, hierro y los aminoácidos, se produce de esta forma.

La pinocitosis, es la absorción de una gota pequena de contenido intestinal por parte de la membrana de la célula epitelial. Permite así que se absorban particulas grandes, como proteínas enteras y en cantidades pequenas.

**** Intestino grueso

El intestino grueso es la localizacion de la absorción del resto del agua y de las sales, de la fermentacion bacteriana, de la sintesis de una pequena cantidad de vitaminas, de almacenamiento y de excrecion. Esta formado por el ciego, colon y recto.

El moco secretado por la mucosa del intestino grueso protege a la pared intestinal de la escoriacion y la actividad bacteriana y proporciona un medio para la aglutinacion de las heces. Los iones de bicarbonato que se secretan intercambiandolos por los iones de cloruro absorbidos contribuyen a neutralizar los productos finales ácidos que produce la accion bacteriana. Se absorbe la mayor parte del agua y el contenido colonico se mueve en direccion anterograda a una velocidad de 5 cm/hora pudiendo absorber algunos nutrientes que persistan.

La defecacion es variable de 3 veces al dia hasta 1 vez por cada 3 dias. El tiempo de transito desde la ingesta por la boca hasta el ano puede variar desde 18 hasta las 72 horas.

Accion bacteriana: la microflora intestinal forma una comunidad que se estima que incluye 400 especies de microorganismos. Los lactobacillus son el principal componente en el tubo digestivo. Mas tarde Escherichia coli se hace predominante en el ileon distal, formada principalmente por anaerobios, de los cuales los mas frecuentes son los Bacteroides. Tambien hay lactobacilos en las heces. Generalmente quedan escasas bacterias por las acciones del ácido clorhidrico, la pepsina y la bilis como agente germicida. Las bacterias colonicas contribuyen a la formación de gases (hidrógeno, dioxido de carbono, nitrogeno y en algunos casos metano) y AGCC (ácidos acetico, propiónico, butirico y lactico). Las bacerias colonicas continuan la digestión de algunos materiales, durante este proceso forman varios nutrientes mediante sintesis bacteriana, como por ejemplo Vitamina K, B12, tiamina y riboflavina.

Una dieta basada en carne, grasa y carbohidratos muy digeribles da lugar a un mayor cociente de bacterias putrefactivas o potecialmente perjudiciales como Pseudomonas, Clostridium, E. coli y Proteus.

Los alimentos probioticos son alimentos concentrados que contienen cantidades muy elevadas de bacterias que se consideran saludables o protectoras frente a microorganismos patogenos y las enfermedades. La accion bacteriana también puede dar lugar a la formación de sustancias potencialmente toxicas como amoniaco, indoles, aminas y compuestos fenolicos como indolacetato, tiramina, histamina y cresol.

Despues de salir del intestino delgado, quedan en el quimo algunas pequenas cantiades de carbohidratos de bajo peso molecular y aminoácidos. La eliminacion de los sustratos residuales mediante la sintesis de AGCC se denomina rescate colonico. Los AGCC que se producen por la fermentacion se absorben rápidamente y arrastran agua con ellos. Tambien actúan como combustible para los colonocitos y los microorganismos intestinales, estimulan la proliferacion y la diferenciacion de los colonocitos, estimulan la absorción de electrolitos y agua y reducen la carga osmotica de los azucares no absorbidos. Tambien pueden ayudar a retrasar el movimiento del contenido digestivo y participan en otras diversas funciones reguladoras.

Las recomendaciones actuales proponen el consumo de entre 24 y 38 gr de fibra dietetica al dia procedente de frutas, verduras, legumbres, semillas y granos enteros para:

 1. Mantener la salud de las células que revisten el colon.
 2. Prevenir una presion intracolonica excesiva.
 3. Prevenir el estrenimiento y mantener una poblacion microbiana estable y saludable.

***** Digestion y absorción de tipos especificos de nutrientes

 Carbohidratos y fibra
 ---------------------

 Se consumen la mayor parte mediante almidones, disacáridos y monosacáridos. Los almidones son moléculas grandes formadas por cadenas rectas o ramificadas de moléculas de azúcar que están unidas entre sí. La fibra de la dieta también esta formada principalmente por cadenas y ramas de moléculas de azúcar. Los seres humanos tienen la capacidad de digerir el almidon, pero no la mayor parte de las formas de fibra.

 La enzima amilasa salivar (ptialina), con pH neuro o ligeramente alcalino, comienza la accion digestiva hidrolizando una pequena cantidad de moléculas de almidon para obtener fragmentos mas pequenos. La amilasa se inactiva despues en contacto con el ácido clorhidrico.

 La amilasa pancreatica hidroliza las grandes moléculas de almidon para dar lugar a maltosa, maltotriosa y dextrinas de <<alfa-limite>> procedentes de las ramas de la amilopectina. Las enzimas del borde del cepillo de los enterocitos hidrolizan aun mas los disacáridos y los oligosacáridos para obtener monosacáridos.

 Los monosacáridos resultantes (glucosa, galactosa y fructosa) atraviesan las células de la mucosa y pasan hacia el torrente sanguineo a través de los capilares de las vellosidades, desde donde son transportados por la vena porta hasta el hígado. A concentraciones baja de glucosa y galactosa se absorben mediante transporte activo, principalmente por un transportador dependiente del sodio, el contransportador de glucosa (galactosa) (SGLT1). A mayores concentraciones luminales de glucosa, GLUT 2 se convierte en el principal transportador facilitador hacia el interior de la célula intestinal. La fructosa se absorbe mas lentamente y utiliza GLUT 5 y el transportador facilitador desde la luz. Se utiliza GLUT 2 para transportar tanto glucosa como fructosa a través de las células intestinales hacia la sangre.

El transporte de los monosacáridos dependiente de sodio es el motivo por el que se utilizan bebidas con sodio y glucosa para rehidratar a los lactantes con diarrea y a los atletas que han perdido demasiado líquido. La glucosa se transporta desde el hígado hacia los tejidos, aunque parte de ella se almacena en el hígado y en los musculos en forma de glucógeno. La mayor parte de la fructosa al igual que la galactosa, es transportada hacia el hígado, donde se convierte en glucosa.

 Hidrolisis gradual de grandes moléculas de almidon en glucosa por las enzimas digestivas:

    Moleculas de almidon --> moléculas de dextrina --> moléculas de dextrina de menor tamaño --> moléculas de dextrina de menor tamaño --> moléculas de dextrina de menor tamaño aumentando el numero de moléculas de maltosa --> moléculas de glucosa
                             (hidro. enzima salival)   (hidro. enzima salival)                   (hidro. enzima pancreatica)               (hidro. enzima intestinal)

 Algunas formas de carbohidratos no pueden ser absorbidas por los seres humanos porque ni la amilasa salivar ni la pancreatica tienen la capacidad de hidrolizar los enlaces beta1-2 y beta1-4 que conectan los azucares que la constituyen: celulosa, hemicelulosa, pectina, goma y otras formas de fibra no pueden ser absorbidas.

 Proteinas
 ---------

 En general las proteínas animales se digieren con mayor eficiencia que las vegetales. La digestión de las proteínas comienza en el estomago, donde algunas de las proteínas son hidrolizadas para dar proteosas, peptonas y polipéptidos grandes. El pepsinogeno inactivo se convierte en la enzima pepsina cuando entra en contacto con el ácido clorhidrico y con otras moléculas de pepsina. Al contrario que cualquiera de las demas enzimas proteoliticas, la pepsina digiere el colageno, que es la principal proeina del tejido conectivo. La mayor parte de de la digestión de las proteínas tiene lugar en la procion superior del intestino delgado, aunque continua durante todo el tubo digestivo.

 +-------------------------------------------------------------------------------+
 |                                  Almidon                                      |
 |                                                                               |
 |                                                                               |
 | Sacarosa     Dextrina          Matotriosa       Maltosa        Lactosa        |  Luz intestinal
 |    |    \             \            |             /            /   |           |
 |    v     \-------------------\     |     /-------------------     v           |
 | Fructosa                        Glucosa          Na+         Galactosa        |
 |    |                               |         /        \          |            |
 +--GLUT 5                          SGLT 1                   -   SGLT 1----------+
 |                                                                               |
 |                                                                               |
 | Fructosa                        Glucosa                      Galactosa        |  Interior del enterocito
 |                                                                               |
 |                                                                               |
 +--------------  GLUT 2                          GLUT 2-------------------------+
 |                   |                              |                            |
 |                   v                              v                            |  Hacia la luz intestinal
 |                                                                               |
 +-------------------------------------------------------------------------------+

 El contacto entre el quimo y la mucosa intestinal estimula la liberación de enterocinasa, una enzima que transforma el tripsinogeno pancreatico inactivo en tripsina activa, que es la principal enzima pancreatica que digiere proteínas. La tripsina a su vez, activa a las demas enzimas proteoliticas pancreaticas. La tripsina, la quimotripsina y el carboxipeptidasa pancreaticas escinden proteínas intactas y continuan la escision que comenzo en el estomago hasta que se forman polipéptidos pequenos y aminoácidos.

 Las peptidasas proteoliticas localizadas en el borde del cepillo también actúan sobre los polipéptidos, escindiendolos para dar aminoácidos, dipéptidos y tripéptidos.  La fase final de la digestión de las proteínas tiene lugar en el borde en cepillo, donde algunos de los dipéptidos y tripéptidos son hidrolizados hasta los aminoácidos que lo forman por las hidrolasas peptídicas.

 Los productos finales de la digestión de la digestión de las proteínas se absorben en forma de aminoácidos y de péptidos pequenos. Son necesarias varias moléculas transportadoras para los diferentes aminoácidos, debido a las diferencias de tamaño, polaridad y configuración de los diferentes aminoácidos. Tambien se absorben grandes cantidades de dipéptidos y tripéptidos hacia las células intestinales utilizando un transportador peptidico (PEPT1), siendo una forma de transporte activo. Los péptidos y aminoácidos absorbidos son tranportados despues hasta el hígado a través de la vena porta para su metabolismo por el hígado y son liberados hacia la circulación general. Finalmente solo se encuentra el 1% de las proteínas ingeridas en la fase final del yeyuno.

 Lípidos
 -------

 El 97% de los lípidos de la dieta están formados por triglicéridos, el resto por fosfolípidos y colesterol. Pequenas cantidades de grasa son digeridas en la boca por la lipasa lingual y en el estomago por la accion de lipasa gastrica (tributirinasa). La mayor parte de la digestión de las grasas tiene lugar en el intestino delgado por la accion de la lipasa pancreatica.

 La entrada de grasas y proteínas en el intestino delgado estimula la liberación de CCK y enterograstrona, que inhiben las secreciones y la motilidad del estomago, retrasando la liberación de los lípidos. Entre otras funciones, la CCK estimula la secrecion biliar y pancreatica. La combinacion de la accion peristaltica del intestino delgado y de la accion tensioactiva y emulsionante de la bilis reduce los globulos de grasa hasta gotitas pequenas, haciendo la digestión mas accesible desde la enzima mas potente que digiere los lípidos, la lipasa pancreatica.

 La bilis es una secrecion hepatica formada por ácidos biliares, pigmentos biliares, sales inorganicas, algunas proteínas, colesterol, lecitina y compuestos como farmacos destoxificados que son metabolizados y secretados por el hígado.

 Los ácidos grasos libres y los monoglicéridos que se producen por la digestión forman complejos con las sales biliares denominados micelas. Las micelas facilitan el paso de los lípidos a través del entorno acuoso de la luz intestinal hasta el borde en cepillo. Las micelas liberan los componentes lipidicos y vuelven a la luz intestinal. La mayor parte de las sales biliares son reabsorbidas de forma activa en el ileon terminal y vuelven al hígado para volver a entrar en el tubo digestivo con las secreciones biliares (este fenomeno de reciclado se conoce como circulación enterohepatica).

 En las células de la mucosa los ácidos grasos y los monoglicéridos se vuelven a ensamblar para dar nuevos triglicéridos, siendo algunos de estos sometidos a una digestión adicional para dar ácidos grasos y glicerol y despues se vuelven a ensamblar para formar triglicéridos, siendo estos junto con el colesterol, las vitaminas liposolubles y los fosfolípidos, rodeados por una cubierta de beta-lipoproteína, formando quilomicrones. Los globulos de lipoproteínas pasan hacia el sistema linfatico en lugar de entrar en la sangre portal y son transportados hacia el conducto toracico y drenados hasta la circulación sistemica en la unión de las venas yugular interna izquierda y subclavia izquierda. A continuacion los quilomicrones son reempaquetados en lipoproteínas de muy baja densidad y transportados principalmente hasta el tejido adiposo para su metabolismo y almacenamiento.

 Las vitaminas A, D, E y K también se absorben en forma de micelas, aunque se pueden absorber las formas hidrosolubles de los suplementos de las vitaminas A, E y K y el caroteno sin la presencia de sales biliares.

 Los grasos ácidos de 8 a 12 átomos de carbono, se pueden absorber directamente hacia las células de la mucosa colonica sin la presencia de bilis ni la formación de micelas. Despues de entrar en las células de la mucosa, pueden pasar directamente sin esterificacion, hasta la vena porta, que los transporta hasta el hígado.

 Vitaminas
 ---------

 Se absorben y digieren a través de la mucosa, principalmente en el intestino delgado. Ademas de los correspondientes mecanismos pasivos y de transporte, diversos factores afectan a la biodisponibilidad de las vitaminas y los minerales, como la presencia o ausencia de otros nutrientes especificos, ácidos o alcalis, fitatos y oxalatos. Cada dia se secretan 8 o 9 litros de líquido desde el tubo digestivo que actua como disolvente, vehiculo para las reacciones quimicas y medio de transferencia para distintos nutrientes. La mayoria de las vitaminas y agua pasa sin modificaciones desde el intestino delgado hasta la sangre mediante difusión pasiva, aunque se podrian utilizar mecanismos para transportar vitaminas individuales a través de la mucosa digestiva. Los farmacos se absorben por diversos mecanismos y pueden compartir los mecanismos para la absorción de nutrientes hacia las células intestinales o competir por ellos.

 Minerales
 ---------

 Su absorción es compleja, especialmente la de los minerales catiónicos, como el selenio, que están disponibles para la absorción por el proceso de quelacion, en la que un mineral esta unido a un ligando (habitualmente un ácido, un ácido organico o un aminoácido), de modo que esta en una forma capaz de ser absorbida hacia las células intestinales.

 La absorción del hierro y zinc, comparte varias caracteristicas ya que la eficiencia de la absorción depende en parte de las necesidades del huesped. Utilizan al menos una proteína transportadora, y cada uno de ellos tiene mecanismos para aumentar la absorción cuando los depositos son inadecuados. Los fitatos y los oxalatos reducen la absorción de hierro y de zinc y su reabsorción es mejor cuando proceden de fuentes animales que cuando son de origen vegetal. La absorción de zinc esta reducida cuando hay cantidades desproporcionadamente elevadas de magnesio, calcio y hierro.

 La absorción de calcio hacia el interior del enterocito se produce a través de canales en la membrana del borde en cepillo, donde se una a una proteína transportadora especifica para su transporte a través de la membrana basolateral. El proceso esta regulado por la presencia de vitamina D.

 El fosforo se absorbe por un cotransportador de sodio y fosforo que también esta regulado por la vitamina D o por una baja ingesta de fosforo.

 El tubo digestivo es la localizacion de importantes interacciones entre los minerales. El aporte de grandes cantidades de hierro o de zinc puede reducir la absorción de cobre.

 La presencia de cobre, puede reducir la absorción de hierro y de molibdeno.

 La absorción de cobalto esta aumentada en pacientes con deficiencia de hierro, pero en cobalto y el hierro compiten entre sí e inhiben su absorción mutuamente.

 Los minerales se transportan por la sangre unidos a transportadores proteicos. La unión de proteínas puede ser especifica (por ejemplo transferrina que se une al hierro) o general (por ejemplo albumina que se une a diversos minerales). Una fraccion de diversos minerales también es transportada en el suero en forma de complejos con aminoácidos o con péptidos. Las proteínas transportadoras especificas habitualmente no están saturadas por completo, la capacidad de reserva puede actuar como amortiguador frente a una exposicion excesiva, por lo que la toxicidad de minerales se produce solo despues de superar esta capacidad amortiguadora.

 Factores que afectan a la digestión
 -----------------------------------

 El aspecto, olfato, el gusto por los alimentos, influyen sobre la digestión. La vista, olfato, gusto e incluso el pensamiento en el alimento aumenta la secrecion de hormonas digestivas, líquidos y enzimas y la actividad muscular del tubo digestivo.

 Despues de la ingestion de alimentos, los productos digestivo activan mecanismos de retroalimentacion que inhiben la actividad digestiva y reducen la ingesta de alimentos. El miedo, la ira y la preocupacion estimulan al hipotalamo para que active el sistema nervioso autonomo, que a su vez reduce las secreciones, inhibe el peristaltismo y retrasa la propulsion del alimento al aumentar el tono de los esfinteres. Los olores intensos, los estimulos perjucidiales y las emociones muy intensas pueden inducir nauseas y vomitos. El envejecimiento afecta a la digestión por una disminucion de la velocidad de recambio de proteínas, reduccion de la sintesis de hormonas antagonicas y una ingesta inadecuada.

 Varios nutrientes, se pueden destruir con una coccion prolongada y alteran la digestibilidad de los alimentos. Sin embargo, algunos alimentos tienden a ser mas seguros y digeribles que los alimentos crudos, por ejemplo la coccion de la carne ablanda el tejido conectivo, facilita la masticacion y hace que la carne sea mas accesible para los jugos digestivos. La coccion hablanda la fibra de la dieta, haciendo que algunos tipos de fibra se puedan fermentar con mas facilidad y hacen que aumenten los nutrientes digeribles unidos a la fibra. Las frutas y verduras se deben consumir crudas porque sus enzimas inherentes para la digestión de carbohidratos o proteínas facilitan la digestión de los alimentos y se destruyen con la coccion. Durante el refinado del grano para obtener panes y cereales se pierden muchos de los nutrientes, productos fitoquimicos y materiales fibrosos. El enriquecimiento reemplaza varios de los nutrientes perdidos, pero no la fibra dietetica ni los productos fitoquimicos.

***** Sistema inmunitario

 Funciones del sistema inmunitario innato:

 1. Poner en marcha y posteriormente desactivar un ataque frente a los patogenos invasores transitorios que se abren camino por el tubo digestivo.
 2. Impedir que los componentes antigenicos de los alimentos (e.g. péptidos) interactuen o sean absorbidos y produzcan respuestas alergicas a nivel local y sistemático.
 3. Tolerar la mezcla de aproximadamente 400 especies de bacterias <normales> que residen en el tubo digestivo, sus secreciones y sus productos de degradacion (e.g. componentes de la pared celular, ADN, proteínas).

 Uso terapeutico para la flora intestinal mediante el consumo de:

 Probioticos: alimentos o concentrados de microorganismos vivos que contribuyen a un entorno microbiano saludable y suprimen los microorganismos potencialmente perjudiciales.
 Prebioticos: componentes oligosacáridos de la dieta (e.g. fructooligosacáridos, inulina) que son los sustratos energeticos preferidos de los microorganismos <amistosos> del tubo digestivo.
 Simbioticos: son una combinacion de probioticos y prebioticos.

*** Energia
**** Componentes y consumo de energía

Se define la energía como capacidad para realizar un trabajo. La fuente ultima de toda la energía en los organismos vivos es el sol.

El cuerpo tiene la capacidad unica de modificar la mezcla de combustible de carbohidratos, proteínas y grasas para adaptarse a las necesidades energeticas.

GET (Gasto Energetico Total): La energía se consume en el cuerpo en forma de metabolismo basal, efecto termico de los alimentos y termogenia debida a la actividad. Estos 3 componentes forman el GET.
GEB (Gasto Energetico Basal): Cantidad minima de energía consumida que es compatible con la vida. Refleja la cantidad de energía que se utiliza durante 24h mientras esta en reposo fisico y mental en un entorno termicamente neutro que evita la activacion de procesos generadores de calor como el temblor.
MB (Metabolismo Basal): Las mediciones se realizan a primera hora, antes de haber realizado cualquier actividad fisica, y de 10 a 12 h despues de ingerir cualquier alimento, bebida o nicotina. Representa el 60 o 70% del gasto energetico total.
TMR (Tasa Metabolica en Reposo): Si no se cumple cualquiera de las condiciones para medir el MB, se debe denominar TMR. Alimentos, cafeina, alcohol y nicotina aumentan el TMR.
GER (Gasto Energetico en Reposo): Energia consumida en las actividades necesarias para mantener las funciones corporales normales y la homeostasis. Dichas actividades incluyen la respiracion, circulación, sintesis de compuestos organicos, bombeo de iones a través de las membranas, energía necesaria para el sistema nervioso central y mantenimiento de la temperatura corporal.

ETA (Efecto Termico de los Alimentos): es el aumento del gasto energetico asociado al consumo de alimentos. Supone el ~10% del GET. El ETA varia con la composicion de la dieta; la grasa se metaboliza de forma eficiente con un desperdicio del 4%, los carbohidratos tienen un desperdicio del 25% cuando se convierten en grasas para su almacenamiento. Los alimentos picantes aumentan el ETA hasta un 33%.
Termogenia obligatoria: energía necesaria para digerir, absorber y metabolizar los nutrientes, incluyendo la sintesis y el almacenamiento de proteínas, grasas y carbohidratos.
Termogenia adaptativa/facultativa: es el exceso de energía consumido ademas de la termogenia obligatoria, debido posiblemente a la ineficiencia metabolica del sistema estimulado por la actividad nerviosa simpatica.
TA (Termogenia por Actividad): es la energía consumida durante el ejercicio para mantener la forma fisica.
NEAT (Termogenia por Actividad no Relacionada con el Ejercicio): son las actividades de la vida diaria (mascar chicle, pasear, ir de compras, etc).
ECOP (Exceso de Consumo de Oxigeno Postejercicio): la duración y la magnitud de la actividad fisica aumentan el ECOP.


**** Medicion del consumo de energía

Caloria: cantidad de energía calorica necesaria para elevar 1 C la temperatura de 1 L de agua a 15 C.

kcal, Cal, C: La cantidad de agua que participa en el metabolismo de los alimentos es bastante grande, por lo que se utiliza la Kcal o Cal (1000 calorias)

julio, J: mide la energía expresada como trabajo mecanico. Es la cantidad de energía necesaria para acelerar con una fuerza de 1 Newton (N) durante 1 distancia de 1 m. 1 kcal = 4,184 kJ.

Calorimetria directa: estima el gasto energetico basandose en la cantidad de calor producida por una persona situada dentro de una estructura.
Calorimetria indirecta: estima el gasto energetico basandose en el consumo de oxigeno y produccion de dioxido de carbono en un periodo dado.

CR (Cociente Respiratorio): CR = moles de CO2 espirados/moles de O2 consumidos. Midiendose las kilocalorias por cada m2 de superficie corporal por hora y extrapolada a 24h. El CR depende de la mezcla de combustibles que se metaboliza, siendo el CR para los carbohidratos de 1, ya que el numero de moléculas de dioxido de carbono que se producen es igual al numero de moléculas de oxigeno que se consumen.

 Carbohidratos = CR 1
 Dieta mixta   = CR 0.85
 Proteinas     = CR 0.82
 Grasas        = CR 0.7

AMD (Agua Doblemente Marcada): estimacion de la produccion de dioxido de carbono a partir de las diferencias de velocidades de eliminacion del hidrógeno y del oxigeno corporales

**** Estimacion de las necesidades energeticas

Las estimaciones de las necesidades energeticas se deben basar en las estimaciones del gasto energetico.

NEE (Necesidades Energeticas Estimadas): son el promedio de la ingesta energetica con la dieta que se prevee que permitira mantener el equilibrio energetico en un adulto sano de una edad, sexo, peso, altura y nivel de actividad fisica definidos con una buena salud.

Ingesta Dietetica de Referencia (IDR): necesidades energeticas en personas activas

 NAF y NEE según edad
 |-------------------+-----------------------------------------------------------------------------------------|
 | Edad              | NAF activo, NEE (kcal/dia)                                                              |
 |-------------------+-----------------------------------------------------------------------------------------|
 | Adultos > 18 anos | 3067 (restando 10 kcal/dia) para los varones y 7 para las mujeres por encima de 19 anos |
 |                   |                                                                                         |
 |-------------------+-----------------------------------------------------------------------------------------|

NAF (Niveles de actividad fisica): categorias de estilo de vida; sedentario, poco activo (3.2 km/dia), activo (11.3 km/dia) y muy activo (27.4 km/dia) para gente que camina de 4.8 a 6.4 km/h..

 Ecuaciones de prediccion de NEE (Necesidades Energeticas Estimadas) según el nivel de actividad fisica
 |--------------------------------------------------------------------------------|
 | NEE para varones de 19 anos de edad y mas (IMC 18,5-25 kg/m2)                  |
 |--------------------------------------------------------------------------------|
 | NEE = GET                                                                      |
 | NEE = 662 - 9.53 x edad (anos) + AF * (15.91 x peso [kg] + 539.6 x altura [m]) |
 | Donde:                                                                         |
 | AF = coeficiente de actividad fisica:                                          |
 | AF = 1.48 si se estima que el NAF es >= 1.9 y < 2.5 (muy activo)               |
 |--------------------------------------------------------------------------------|

IMC (Indice de Masa Corporal): se determina dividiendo el peso en kg por el cuadrado de la altura en metros.

El consumo energetico se determina por la cantidad de oxigeno metabolizado por el cuerpo.

MET (Equivalentes Metabolicos): MET de 1 es el oxigeno metabolizado en reposo (3.5 mL de oxigeno por cada kg de peso corporal por minuto en adultos). Se puede expresar como 1 kcal por kg de peso corporal por hora.

E.g. de un adulto que pesa 65 kg y camina de forma moderada a una velocidad de 6.4 km/h (que es un valor MET de 4.5) durante 1 h consumira 293 calorias (4.5 kcal * 65 kg * 1 = 293).

Para estimar las necesidades energeticas de una persona utilizando las escuaciones del NEE, es necesario asignar un valor de NAF a esa persona. El valor del NAF puede estar influido por las diversas actividades que se realizan durante el dia y se denomina cambio de nivel de actividad fisica (Δ NAF). Para determinar el Δ NAF se toma la suma de los Δ NAF de cada una de las actividades realizadas durante 1 dia a partir de la siguiente tabla:

 Categorias de nivel de actividad fisica y equivalencia de paseo
 |------------------+----------------+-------------------------------------------------|
 | Categoria de NAF | Valores de NAF | Equivalencia de paseo (km/dia a 4.8 - 6.4 km/h) |
 |------------------+----------------+-------------------------------------------------|
 | Sedentario       |         1-1.39 |                                                 |
 | Poco activo      |       1.4-1.59 | 2.2, 3.5, 4.7 para NAF = 1.5                    |
 | Activo           |       1.6-1.89 | 4.8, 7.1, 9.3 para NAF = 1.6                    |
 |                  |                | 8.5, 11.8, 15.9 para NAF = 1.75                 |
 | Muy activo       |        1.9-2.5 | 12.1, 16.6, 22.5 para NAF = 1.9                 |
 |                  |                | 19.8, 26.9, 36.2 para NAF = 2.2                 |
 |                  |                | 27.4, 37, 49.9 para NAF = 2.5                   |
 |------------------+----------------+-------------------------------------------------|
 Los valores inferior, medio y superior del numero de km/dias se aplican a personas de peso relativamente elevado (120 kg), medio (70 kg) y ligeros (44 kg) respectivamente

Para calcular el valor NAF para 1 dia se toma la suma de las actividades y se añade el GEB (1) mas el 10% para tener en consideracion el ETA (1 + 0.1 = 1.1)

**** Calculo de la energía de los alimentos

No toda la energía de los alimentos esta disponible  para las células del cuerpo. Los procesos de digestión y absorción no son completamente eficientes, y la porcion nitrogenada de los aminoácidos no se oxida, sino que se excreta en forma de urea. Por lo que la energía disponible de los alimentos se expresa en valores redondeados ligeramente por debajo.

 Proteinas      4 kcal/gr
 Grasas         9 kcal/gr
 Carbohidratos  4 kcal/gr
 Alcohol        7 kcal/gr
 Fibra          2 kcal/gr (carbohidrato no disponible, ya que se resiste a la digestión y absorción)

*** Nutrientes y metabolismo
**** Macronutrientes
***** Carbohidratos

Formados por carbono, hidrógeno y oxigeno en proporciones C:O:H2

****** Monosacáridos

Los seres humanos solo pueden absorber y utilizar un pequeno numero de los muchos monosacáridos. Los monosacáridos pueden tener de 3 a 7 átomos de carbono, aunque los monosacáridos mas importantes en la dieta humana son las 3 hexosas de 6 átomos de carbono: glucosa, galactosa y fructosa. Todas hexosas tienen la misma formula quimica, aunque difieren mucho entre sí, debido a sus pequenas diferencias en la estructura quimica, algunas debidas a la presencia de carbonos quirales.

Un carbono quiral es un carbono que tiene unidos cuatro átomos o grupos diferentes, estos grupos pueden aparecer en posiciones diferentes, dando lugar a isomeros.

  Hexosas
  -------

  α-D-glucosa       β-D-galactosa      β-D-fructosa

     H   O             H   O              H   O
      \ //              \ //               \ //
  1    C           1     C             1  H-C-OH
       |                 |                  |
  2  H-C-OH        2   H-C-OH          2  H-C=O
       |                 |                  |
  3 HO-C-H         3  HO-C-H           3 HO-C-H
       |                 |                  |
  4  H-C-OH        4  HO-C-H           4  H-C-OH
       |                 |                  |
  5  H-C-OH        5   H-C-OH          5  H-C-OH
       |                 |                  |
  6    CH₂OH       6     CH₂OH          6    CH₂OH

Ademas de formar isomeros, los monosacáridos (del grupo aldehido y del grupo cetona) se ciclan, formando estructuras anulares que dan lugar a mas isomeros.

Las enzimas del cuerpo son estereoespecificas y solo pueden actuar sobre isomeros especificos, por lo que solo 3 isomeros de monosacáridos tienen relevancia en el metabolismo humano: α-D-glucosa, β-D-galactosa, β-D-fructosa. Todos los demas carbohidratos se deben digerir de forma eficaz para obtener estos monosacáridos componentes para su absorción.

La dextrosa es la glucosa que se produce a partir de la hidrolisis del almidon de maiz.

El azúcar sanguineo, se refiere a la glucosa, y el encefalo tiene una elevada dependencia de un aporte regular y predecible.

La fructosa o azúcar de la fruta. A medida que las frutas maduran, las enzimas escinden la sacarosa en glucosa y fructosa, que da un sabor mas dulce.

El sirope de maiz se fabrica enzimaticamente cambiando la glucosa del almidon de maiz por fructosa.

La galactosa se produce a partir de la lactosa o azúcar de la leche por hidrolisis durante el proceso digestivo.

Tanto la galactosa como la fructosa se metabolizan en el hígado por incorporacion a las vías metabólicas de la glucosa. La fructosa se incorpora en la via glucotidica, aunque evita una importante enzima de control en la via.

 Dulzor de los azucares y edulcorantes
 |---------------------------------------+------------------|
 | Sustancia                             | Valor del dulzor |
 |---------------------------------------+------------------|
 | Azucares                              |                  |
 |---------------------------------------+------------------|
 | Fructosa                              | 173              |
 | Azúcar invertido                      | 130              |
 | Sacarosa                              | 100              |
 | Glucosa                               | 74               |
 | Sorbitol                              | 60               |
 | Manitol                               | 50               |
 | Galactosa                             | 32               |
 | Maltosa                               | 32               |
 | Lactosa                               | 16               |
 |---------------------------------------+------------------|
 | Edulcorantes Artificiales             |                  |
 |---------------------------------------+------------------|
 | Ciclamato (prohibido en USA)          | 30               |
 | Aspartamo (nutritivo, tiene calorias) | 180              |
 | Acesulfamo-K                          | 200              |
 | Sacarina                              | 300              |
 | Sucralosa                             | 600              |
 | Alitamo (pendiente de autorizacion)   | 2000             |
 |---------------------------------------+------------------|

****** Disacáridos

Los 3 disacáridos mas importantes en nutricion son la sacarosa, lactosa y maltosa. Estos azucares están formados por monosacáridos unidos por un enlace glucosidico entre el carbono activo del aldehido o de la cetona y un hidroxilo especifico de otro azúcar.

La sacarosa, se forma cuando se unen entre sí la glucosa y la fructosa.

El azúcar invertido es también una forma natural de azúcar (glucosa y fructosa no unidas entre sí y en proporcion 1:1).

La lactosa, esta formada por glucosa y galactosa. Se sintetiza casi exclusivamente en las glandulas mamarias de los animales hembras lactantes.

La maltosa esta formada por 2 moléculas de glucosa, es rara encontrarla en la naturaleza, aunque a veces se forma por la hidrolisis de los polimeros de almidon durante la digestión.

Las enzimas que se encuentran en el borde del cepillo, rompen (digieren) los enlaces entre las moléculas de disacáridos y son especificas para cada enlace particular.

Unicos enlaces que se hidrolizan en el borde del cepillo:

 - La sacarasa escinde el enlace α entre la glucosa (C-1) y la fructosa (C-2).
 - La lactasa escinde el enlace β entre la galactosa (C-1) y la glucosa (C-4).
 - La maltasa escinde el enlace α entre la glucosa (C-1) y la glucosa (C-4).
 - La isomaltasa escinde el enlace α entre la glucosa (C-1) y la glucosa (C-6).

Los carbohidratos que contienen otro tipo de enlaces no se pueden digerir y se califican como fibra dietetica.

****** Oligosacáridos

Son polimeros de bajo peso molecular que contienen de 2 a 20 moléculas de azúcar. Al ser pequenos son hidrosolubles. Las moléculas mas grandes no son hidrosolubles y se clasifican como fibra dietetica.

****** Polisacáridos

Son carbohidratos con mas de 10 unidades de monosacáridos. Las plantas lo almacenan en granulos de almidon formados por cadenas rectas de glucosas unidas por enlaces α-1,4 con ramas unidas por enlaces α-1,6, formando una estructura granular compleja.

Las plantas sintetizan 2 tipos de almidon:

 - Amilosa: molécula linear de menor tamaño (10⁵ a 10⁶ daltons) que tiene una ramificacion menor al 1%.
 - Amilopectina: esta muy ramificada, contiene un 5% de enlaces α-1,6 y tiene un peso molecular muy elevado (10⁷ a 10⁸ daltons).

Las dextrinas se producen por el proceso digestivo y son grandes polisacáridos de glucosa lineales de longitud intermedia escindidos a partir del almidon de elevado contenido en amilasa por la α-amilasa, posteriormente pueden ser digeridas por la enzima isomaltasa de la mucosa para dar glucosa.

Los animales utilizan (al contrario que las plantas) los carbohidratos principalmente para mantener la concentracion sanguínea de glucosa entre las comidas, y así garantizar un aporte continuo. Todas las células (y principalmente el hígado y el musculo) almacenan carbohidratos en el polimero glucógeno, que se mueve con faicilidad. Con todos los carbohidratos, el glucógeno se almacena hidratado con agua, siendo la molécula voluminosa y poco adecuada para el almacenamiento de energía a largo plazo.

El varon medio de 70 kg, almacena solo un aporte de combustible de 17 horas en forma de glucógeno, en comparacion a los dos meses almacenado en forma de grasa. Estimandose que si todos los depositos de energía humanos fueran glucógeno, deberiamos pesar 27 kg mas.

En el musculo se almacenan aproximadamente 150 gr de glucógeno, que puede aumentar hasta 5 veces con el entrenamiento fisico, pero que no esta disponible para mantener la glucosa sanguínea. Es el deposito de glucógeno del hígado normal (~90 gr) el que participa en el control hormonal de la glucosa sanguínea.

****** Control hormonal de la glucosa sanguínea

El cuerpo debe mantener la glucosa sanguínea a una concentracion minima de 70 a 100 mg/100 mL para aportar combustible al encefalo, el sistema nervioso central y otros consumidores obligados de glucosa.

La insulina, es la principal hormona anabolica y es responsable del almacenamiento y la utilizacion del combustible. Es sintetizada por las células β de los islotes de Langerhans del pancreas y es liberada hacia el torrente sanguineo en respuesta al aumento posprandial de la glucosa sanguínea, aunque también se puede estimular en menor medida por la ingestion de proteínas o infusion de aminoácidos o de cuerpos cetonicos, así como hormonas digestivas, actividad del nervio vago y algunos farmacos.

La insultina se une a receptores de las células musculares y adiposas y facilita la entrada de glucosa mediante transportadores GLUT 4 especializados.

En el hígado, la insulina facilita la oxidación de la glucosa y la sintesis de glucógeno.

En situación de ayunas las células α de los islotes de Langerhans secretan glucagon. Esta hormona actua principalmente en el hígado estimulando la hidrolisis del glucógeno para mantener la concentracion sanguínea de glucosa. Si no hay insulina, el glucagon inhibe la oxidación hepatica de glucosa y estimula la gluconeogenia, que como resultado es la vuelta de la concentracion sanguínea de glucosa al intervalo normal.

El ayuno también estimula la liberación de adrenalina desde la medula suprarrenal y de noradrenalina en las terminaciones nerviosas perifericas. Estas hormonas actúan principalmente sobre el musculo movilizando glucógeno y sobre los adipocitos liberando triglicéridos.

Las concentraciones de adrenalina y noradrenalina aumentan cuando una persona esta enfadada o tiene miedo. En estas condiciones es necesaria la glucosa para proporcionar la energía adicional para la respuesta ante la crisis. Los glucocorticoesteroides aumentan la concentracion sanguínea de glucosa, principalmente estimulando la gluconeogenia.

****** Fibra dietetica y fibra funcional

Las fibras dietiticas son los componentes intactos de las plantas que no son digeribles por las enzimas digestivas.
Las fibras funcionales son los carbohidratos no digeribles que se han extraido o fabricado a partir de las plantas.

Estos dos tipos de fibras tienen funciones fisiologicas beneficiosas para el tubo digestivo y reducen el riesgo de algunas enfermedades.

- Homopolisacáridos: son unidades repetidas de la misma molécula.
  - Celulosa: homopolisacárido formado por moléculas de glucosa unidas por enlaces β-1-4. La molécula se pliega sobre si misma y se mantiene en su lugar por enlaces de hidrógeno.
  - Beta-glucanos: tienen ramificaciones, lo que hace que sean menos lineales y por tanto mas solubles que la celulosa.
  - Quitina: se encuentra en el exoesquleto de artrópodos y otros marinos.
  - Quitosano: se obtiene de la desacetilizacion de la acetilglucosamina de la quitina.

  Se han estudiado la quitina y el quitosano por su efecto hipocolesterolemiante, ya que la intensa carga positiva del quitosano se une a los lípidos de carga negativa, bloqueando su absorción. Reduciendose la concentracion sanguínea del colesterol en un 64%, pero dando lugar (con el quitosano) a una mala absorción de vitaminas liposolubles y de minerales oseos.

- Heteropolisacáridos: se forman modificando la estructura basica de la celulosa.
  - Hemicelulosa: polimero de glucosa y otros azucares.
  - Pecticas y gomas: contienen azucares y alcoholes con azucares haciendo que las moléculas sean mas hidrosolubles que la hemicelulosa.

- Fructanos: incluyen fructoligosacáridos (FOS), inulina, fructanos de tipo inulina y oligofructosa y están formados por polimeros de fructosa, con frecuencia unidos a una glucosa inicial.
  - Inulina: grupo variado de polimeros de fructosa.
  - Oligofructosa: es un subgrupo de la inulina realmente, que contiene al menos 10 unidades de fructosa. Se digieren mal en el tubo digestivo y por tanto aportan solo 1 kcal/g.

  Los fructanos, al no absorberse en el intestino proximal, se han utilizado como sustitutos del azúcar en pacientes diabeticos. Ademas pueden tener propiedades prebioticas (sustancias alimenticias no digeribles que estimulan selectivamente el crecimiento o la actividad de especies bacterianas beneficiosas que ya residen en el colon y son beneficiosas para el huesped).

- Polisacáridos de las algas: son extraidos de las algas.
- Polidextrosa y otros polioles: son polimeros sinteticos de alcoholes con azucares.
- Lignina: son fibras lenosas que se encuentran en tallos y semillas de frutas y verduras, así como cascara de los cereales. No es carbohidrato realmente, sino polimeros formados por alcoholes y ácidos fenilpropilicos. Los grupos fenilo contienen dobles enlaces conjugados, haciendolos excelentes antioxidantes.

Las fibras no solubles, aumentan la capacidad de retencion de agua. Aumentan la frecuencia de las deposiciones.
Las fibras solubles, suelen formar geles, que dan lugar a un retraso del tiempo de transito digestivo y un retraso o disminucion de la absorción de los nutrientes. Se suelen unir a otros nutrientes, como el colesterol y minerales, y reducen la absorción de estos. Algunos olisacáridos no digeribles, son fermentados por las bacterias intestinales y estimulan la absorción intestinal y retencion de algunos minerales como el calcio, magnesio, cinc y hierro.

Fibras menos solubles:
|----------------+---------------------------+--------------------------+-----------------------------------------------------------------------------------------------------------|
| Tipos de fibra | Principales componentes   | Fuentes                  | Funciones principales                                                                                     |
|----------------+---------------------------+--------------------------+-----------------------------------------------------------------------------------------------------------|
| Celulosa       | Glucosa                   | Trigo, salvado, verduras | Aumenta la capacidad de retener agua, aumentando así el volumen fecal y reduciendo el transito intestinal |
|----------------+---------------------------+--------------------------+-----------------------------------------------------------------------------------------------------------|
| Hemicelulosa   | Xilosa, manosa, galactosa | Salvado, grano entero    | La fermentacion produce ácidos grasos de cadena corta asociados a una reduccion del riesgo de formación   |
| Lignina        | Fenoles                   | Frutas y semillas        | de tumores                                                                                                |
|----------------+---------------------------+--------------------------+-----------------------------------------------------------------------------------------------------------|

Fibras mas solubles:
|----------------+-------------------------------+----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------|
| Tipos de fibra | Principales componentes       | Fuentes                                | Funciones principales                                                                                                                          |
|----------------+-------------------------------+----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------|
| Gomas          | Galactosa y ácido glucoronico | Avena, legumbres, guar, cebada         | Dan lugar a la formación de geles, reduciendo el vaciado gastrico, retrasan la digestión, tiempo de transito intestinal y absorción de glucosa |
|----------------+-------------------------------+----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------|
| Pectinas       | Ácido poligalacturonico       | Manzanas, fresas, zanahorias, citricos | Tambien se unen a minerales, lípidos y ácidos biliares, aumentando la excrecion de ellos y reduciendo el colesterol serico                     |
|----------------+-------------------------------+----------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------|

Fibras funcionales (aisladas o extraidas)
|--------------------------------------+-------------------------+--------------------------------+----------------------------------------------------------------------------------|
| Tipos de fibra                       | Principales componentes | Fuentes                        | Funciones principales                                                            |
|--------------------------------------+-------------------------+--------------------------------+----------------------------------------------------------------------------------|
| Quitina                              | Glucopiranosa           | Cascaras de gambas o langostas | Reduce el colesterol serico                                                      |
|--------------------------------------+-------------------------+--------------------------------+----------------------------------------------------------------------------------|
| Fructanos (incluida inulina)         | Polimeros de fructosa   | Achicoria, cebollas, etc       | Prebiotico que estimula el crecimiento de bacterias beneficiosas en el intestino |
|--------------------------------------+-------------------------+--------------------------------+----------------------------------------------------------------------------------|
| β-glucanos                           | Glucopiranosa           | Salvado de avena y cebada      | Reducen el colesterol serico                                                     |
| Polisacáridos de algas (carragenano) |                         | Aislados de algas              | Formadores de gel; espesantes y estabilizantes (pueden ser toxicos)              |
|--------------------------------------+-------------------------+--------------------------------+----------------------------------------------------------------------------------|
| Polidextrosa, polioles               | Glucosa y sorbitol, etc | Sintetizados                   | Agente formador de masa o sustituto del azúcar                                   |
| Psyllium (plantago)                  |                         | Semillas de plantago           | Elevada capacidad de unión al agua (riesgo de atragantamiento)                   |
|--------------------------------------+-------------------------+--------------------------------+----------------------------------------------------------------------------------|

******* Funcion de la fibra en la digestión

Modificaciones sericas de lípidos con fibras insolubles:
 - Las fibras se unen a los ácidos biliares fecales y aumentan la excrecion del colesterol derivado de los ácidos biliares.
 - Las fibras impiden la absorción de la grasa y el colesterol uniendose a los ácidos biliares o a la grasa de los lípidos.
 - Las bacterias intestinales convierten los oligosacáridos fermentables y la fibra dietetica en ácidos grasos de cadena corta, que reducen los lípidos sanguíneos.

Modulacion prebiotica de las vías metabólicas por la fibra en su fermentacion para dar AGCC (Ácidos Grasos de Cadena Corta):
 - Favorecen la absorción de sodio y agua.
 - Aumentan la proliferacion de los colonocitos.
 - Aumentan la produccion de energía metabolica.
 - Incrementan el flujo sanguineo colonico.
 - Estimulan el sistema nervioso autonomo.
 - Aumentan la sintesis de hormonas digestivas.

Ademas de la fibra, otros nutrientes de las plantas como: taninos, saponinas, lectinas y filatos, interactuan con los macronutrientes, vitaminas y minerales y pueden reducir su absorción.

El ácido fitico o fitato, un anillo de 6 átomos de carbono con un fosfato unido a cada carbono, tiene la capacidad de unirse a iones metalicos y especialmente a calcio, cobre, hierro y cinc. Como el calcio cataliza la accion de la amilasa, que hidroliza el almidon, un exceso de fitatos también reduce la hidrolisis del almidon.

******* Absorcion de la glucosa

Los carbohidratos son digeridos para obtener glucosa, fructosa y galactosa mediante acciones de la α-amilasa y las enzimas del borde digestivo en cepillo en el tubo digestivo superior.

La capacidad de digerir carbohidratos depende de:
 - Disponibilidad relativa del almidon a la accion enzimatica.
 - Actividad de las enzimas digestivas, especialmente la lactasa en el borde del cepillo de la mucosa.
 - La presencia de otros factores dieteticos, como grasa (retrasa el vaciado gastrico), oligosacáridos no absorbibles y fibra dietetica viscosa (pectinas, β-glucanos y gomas), que diluyen la concentracion enzimatica. Asi que las dietas ricas en frutas, verduras, legumbres, frutos secos y granos, tienden a retrasar la absorción de la glucosa.

Una vez digerida, la glucosa se absorbe a través de las células intestinales y se transfiere a la sangre portal para su transporte hasta el hígado. El hígado retira el 50% de la glucosa absorbida para su oxidación y almacenamiento en forma de glucógeno. La galactosa se absorbe activamente y la fructosa se absorbe mediante difusión facilitada también son captadas por el hígado e incorporadas a las vías metabólicas de la glucosa. La glucosa sale del hígado y entra en la circulación sistemática. Solo entonces esta disponible para la captación pendiente de insulina por los tejidos periféricos.

******* Regulacion de los lípidos sanguíneos

La ingesta de grasa no se traduce directamente en modificaciones de los lípidos sanguíneos porque el cuerpo regula las concentraciones de macronutrientes para aportar suministros adecuados de combustible a los tefijos corporales. Ingestas elevadas de carbohidratos pueden dar lugar a grandes liberaciones de insulina. Esta hormona anabolica estimula respuestas compensadoras, como la captación de glucosa dependiente de insulina por el musculo y la grasa y la sintesis activa de glucógeno y de grasa, reduciendose así la concentracion sanguínea de glucosa hasta un intervalo normal. 2 horas despues de una comida la abosrcion intestinal es completa, pero el efecto de la insulina persiste, y la concentracion sanguínea de glucosa disminuye a veces por debajo del intervalo normal. El cuerpo interpreta este estado hipoglucemico como inanicion y secreta hormonas contrarreguladores que liberan ácidos grasos libres a partir de las células grasas. Los ácidos grasos se empaquetan en lipoproteínas transportadoras (lipoproteínas de muy baja intesindad o VLDL) en el hígado, elevando de esta forma los triglicéridos sericos.

***** Grasas y lípidos

****** Estructuras y funciones de los lípidos

La grasa de la dieta se almacena en células adiposas (grasas) localizadas en depositos sobre el armazon humano.

Algunos depositos se consideran como grasa estructural, para mantener la posiciones de los órganos y los nervios del cuerpo, así como los protegen de lesiones y choques.

Los seres humanos también tienen una capa subcutanea de grasa que aisla el cuerpo, conservando el calor corporal.

La grasa de la dieta reducen secreciones gastricas, retrasa el vaciado gastrico y estimula el flujo biliar y pancreatico, facilitando el proceso de digestión.

Lípidos importantes fisiologicamente:

 1. Ácidos grasos
 ----------------

 1.1 Saturados

                                            Grupo carboxilo
                                           /---------------\
                                          |                 |
       H   H   H   H   H   H   H   H   H   H   H   H      O
       |   |   |   |   |   |   |   |   |   |   |   |    //
 CH3 - C - C - C - C - C - C - C - C - C - C - C - C - C
       |   |   |   |   |   |   |   |   |   |   |   |    \
       H   H   H   H   H   H   H   H   H   H   H   H     OH

 1.2 Monoinsaturados

       H   H   H   H   H   H   H       H   H   H   H   H   H      O
       |   |   |   |   |   |   |       |   |   |   |   |   |    //
 CH3 - C - C - C - C - C - C - C - C = C - C - C - C - C - C - C
       |   |   |   |   |   |   |   |       |   |   |   |   |    \
       H   H   H   H   H   H   H   H       H   H   H   H   H     OH

  (trans)

       H   H   H   H   H   H   H   H   H   H   H   H   H   H      O
       |   |   |   |   |   |   |   |   |   |   |   |   |   |    //
 CH3 - C - C - C - C - C - C - C - C = C - C - C - C - C - C - C
       |   |   |   |   |   |   |           |   |   |   |   |    \
       H   H   H   H   H   H   H           H   H   H   H   H    OH

  (cis)

 2. Triglicéridos
 ----------------

          O    H   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H      O
          ||   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |    //
 H₂C - O - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C    (ácido estearico)
   |           |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |    \
   |           H   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H     OH
   |
   |       O   H   H   H   H   H   H   H   H   H   H   H   H   H   H       O
   |       ||  |   |   |   |   |   |   |   |   |   |   |   |   |   |     //
  HC - O - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C     (ácido palmítico)
   |           |   |   |   |   |   |   |   |   |   |   |   |   |   |    \
   |           H   H   H   H   H   H   H   H   H   H   H   H   H   H     OH
   |
   |       O   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H      O
   |      ||   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |    //
 H₂C - O - C - C - C - C - C - C - C - C - C = C - C - C - C - C - C - C - C - C   (ácido oleico)
               |   |   |   |   |   |   |           |   |   |   |   |   |   |    \
               H   H   H   H   H   H   H           H   H   H   H   H   H   H     OH

 \-----/ \--------------------------------------------------------------------------/
    |                                         |
 Glicerol                           Colas de ácidos grasos

 3. Fosfolípidos (lecitina)
 --------------------------

                                   O   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H     O
                                  ||   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   //
                         CH₂ - O - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C - C      (ácido estearico)
                         |             |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   \
                         |             H   H   H   H   H   H   H   H   H   H   H   H   H   H   H    OH
                         |
                         |         O  H   H   H   H   H           H   H           H   H   H   H     O
                         |        ||  |   |   |   |   |           |   |           |   |   |   |   //
           -         O - CH - O - C - C - C - C - C = C - C = C - C = C - C = C - C - C - C - C - C       (ácido araquidonico)
 Cabeza  /   \       |                |   |   |           |   |           |   |   |   |   |   |    \
 polar   \   / - O - P - CH₂          H   H   H           H   H           H   H   H   H   H   H    OH
           -         ||
        Colina       O

 4. Isoprenos-esteroides
 -----------------------

                     /-> Polisoprenoide
       CH₃          /
       |           /
 CH₂ = C - C = CH₂
           |       \
           H        \
                     \
                      \-> Colesterol --> Testosterona

 (moléculas demasiado tediosas para representarlas graficamente)

****** Ácidos grasos

Raras veces aparecen de forma libre en la naturaleza y casi siempre están unidos a un grupo bidrofilo de la cabeza de ácido carboxilico. Aparecen como cadenas hidrocarbonadas no ramificadas y se clasifican según el numero de carbonos, el numero de dobles enlaces y la posición de estos.

La longitud de la cadena y el grado de saturación determinan la temperatura de fusion de una grasa.

En general las grasas son cadenas mas cortas de ácidos grasos o con mas dobles enlaces, son liquidas a temperatura ambiente.

Por numero de carbonos:

 - AGCC (Ácidos Grasos de Cadena Corta): de 4 a 6 átomos de carbono.
 - AGCM (Ácidos Grasos de Cadena Media): de 8 a 14 átomos de carbono.
 - AGCL (Ácidos Grasos de Cadena Larga): mas de 14 carbonos.

Por su composicion:

 - Lípidos simples
   - Grasas neutras: esteres de ácidos grasos con glicerol (monoglicéridos, diglicéridos y triglicéridos).
   - Ceras: esteres de ácidos grasos con alcoholes de elevado peso molecular
 - Lípidos compuestos
   - Fosfolípidos: compuestos de ácido fosforico, ácidos grasos y una base nitrogenada
   - Glucolípidos: compuestos de ácidos grasos, monosacáridos, y una base nitrogenada
   - Lipoproteínas: particulas compuestas de lípidos y proteínas
 - Lípidos miscelaneos
   - Eteroles: vitamina D, colesterol, sales biliares
   - Vitaminas A, E, K.

Por saturación:

 - AGS (Ácido Graso Saturado): todos los puntos de unión de los átomos de carbono y que no están unidos a otro carbono, están unidos a hidrógeno (saturados). Por lo tanto no hay enlaces dobles.
 - AGMI (Ácidos Grasos Monoinsaturados): contienen solo un doble enlace.
 - AGPI (Ácidos Grasos Poliinsaturados): contienen 2 o mas dobles enlaces.

En los AGMI o AGPI se ha eliminado uno o mas hidrógenos, por lo que se forman dobles enlaces entre átomos de carbono adyacentes.

Los ácidos grasos con dobles enlaces son vulnerables a la agresión oxidativa. Por lo que los humanos almacenan generalmente ácidos grasos saturados como el palmítico (C16:0) y estearico (C18:0).

Por su enlace doble (num_atomos_de_carbono:enlaces_dobles ω-posicion_del_primer_enlace_doble_contando_desde_el_extremo_metilo):

 - Omega 3: 20:5, ω-3. Ácido eicosapentaenoico (AEP). Se encuentra en organismos marinos
 - Omega 6: 20:4, ω-6. Ácido araquidonico. Se encuentra en las membranas de los animales terrestres.
 - Omega 7: ω-7.
 - Omega 9: ω-9.

Solo las plantas pueden sintetizar los ácidos grasos omega 3 y 6. Los animales (y los humanos) solo pueden colocar dobles enlaces en una situación tan baja como el omega 9, y por lo tanto no puede sintetizar ni omega 3 ni omega 6..

****** Ácidos grasos esenciales y cociente omega-6/omega-3

Los seres humanos no puede sintetizar omega-3 ni omega-6, pero si pueden desaturar y elongar el ácido linoneico (18:2 n-6) para obtener ácido araquidonico (20:4 n-6) y el ácido α-linonenico o AAL (C18:3 ω-3) para obtener AEP (C20:5 omega-3) y ácido docosahexaenoico o ADHE (C22:6 ω-3). Es por ello, que los ácidos grasos esenciales son realmente los de cadena mas larga, pero si la dieta esencial aporta suficientes cantidades de precursores de cadena mas corta, no es necesario que se aporten directamente los ácidos grasos de cadena mas larga.

Los ácidos grasos de cadena mas corta son componentes importantes de las membranas celulares y precursores de eicosanoides como: prostaglandinas, tromboxanos y leucotrienos.

Los eicosanoides actúan como hormonas localizadas (paracrinas) y tienen múltiples funciones locales. Pueden alterar el tamaño y la permeabilidad de los vasos sanguíneos, alterar la actividad de las plaquetas y contribuir a la coagulación sanguínea, y modificar los procesos de la inflamación, así como tener efectos beneficiosos en distintas enfermedades (cardiovasculares, artrosis y enfermedades inflamatorias).

El exceso de grasos ácidos omega-6 satura a las enzimas que desaturan y elongan los ácidos n-3 y n-6 e impide la conversión de AAL en formas de mayor longitud como AEP y ADHE.

El cociente omega-6/omega-3 y optimo es de 2:1 a 3:1 (4 veces menor que la ingesta tipica actual). Por lo que se recomienda que los humanos consuman mas ácidos grasos omega-3 de fuentes vegetales (obteniendo AAL) y marinas (obteniendo AEP y ADHE).

****** Ácidos grasos trans

Los ácidos grasos insaturados se curvan debido a que los hidrógenos de los carbonos de enlaces dobles se encuentran en un mismo lado. La hidrogenación añade hidrógeno a los aceites líquidos y forma así una grasa solida.

Los ácidos grasos trans tienen un efecto negativo sobre la salud humana debido a su influencia sobre la función de las membranas.

La función de las membranas depende de la configuración tridimensional de los ácidos grasos de la membrana que se encuentran en los fosfolípidos.

Los dobles enlaces cis de la membrana se curvan, permitiendo que los ácidos grasos estén apuestos entre sí de forma laxa, lo que hace que la membrana sea fluida.

Como las proteínas incluidas en una membrana flotan o se hunden, dependiendo de la fluidez de la membrana, la viscosidad de la membrana es importante para la función de las proteínas de la membrana.

Los ácidos grasos trans no se curvan, se aponen entre sí en la membrana tan juntos entre sí como si estuvieran totalmente saturados. Esto provoca cardiopatía isqémica, cáncer y otras enfermedades crónicas, debido a su capacidad para modificar la fluidez de las membranas.

Los ácidos grasos trans también inhiben la desaturación y la elongación del ácido linoleico y del AAL para formar ácidos grasos esenciales de cadena larga. Los AGPI son críticos para el desarrollo del encefalo y otros órganos fetales.

****** Triglicéridos

****** Fosfolípidos

****** Lípidos sinteticos

****** Alcohol (alcohol etílico)


***** Aminoácidos y proteínas

****** Aminoácios esenciales

****** Calidad de las proteínas

****** Equilibrio nitrogenado

***** Uso y almacenamiento de macronutrientes en situación posprandial

***** Catabolismo de los macronutrientes en ayunas
**** Micronutrientes
***** Vitaminas liposolubles

****** Vitamina A

****** Vitamina D

****** Vitamina E

****** Vitamina K

***** Vitaminas hidrosolubles

****** Tiamina

****** Riboflavina

****** Niacina

****** Ácido pantotenico

****** Vitamina B6

****** Folato

****** Vitamina B12

****** Biotina

****** Ácido ascorbico

***** Otros factores similares a vitaminas

****** Colina

****** Carnitina

****** Mioinositol

****** Ubiquinonas

****** Bioflavonoides

***** Minerales

****** Composicion en minerales del cuerpo

****** Calcio

****** Fosforo

****** Magnesio

****** Azufre

***** Microminerales: oligoelementos

****** Hierro

****** Cinc

****** Fluor

****** Cobre

***** Ultraoligominerales

****** Yodo

****** Selenio

****** Manganeso

****** Cromo

****** Molibdeno

****** Cobalto

***** Otros oligoelementos

*** Agua, electrolitos y equilibro ácidobasico
**** Agua corporal
**** Electrolitos
**** Equilibrio ácidobasico
**** Trastornos ácidobasicos
