#+BEGIN_COMMENT’        =========================       ‘#+END_COMMENT
#+BEGIN_COMMENT’           SPORT ORG MODE FILE          ‘#+END_COMMENT
#+BEGIN_COMMENT’        =========================       ‘#+END_COMMENT

* Good habits
  - Sleep early
  - Avoid using the laptop after work
  - Read more about nutrition
  - Prepare good and healthy food
    - Vegan and vegetarian mainly
  - Take care of the teeth
  - Minimalism lifestyle (avoid packaging)
  - Study technical things for the future
  - Read non-technical books
  - Nutrition (decrease)
    - Coffee 3 days a week max
    - Not sugar in the coffee
    - Not salt or too much salt
    - Oil only in the salads
    - Avoid bakery
    - Avoid chips or anything fried
    - Eat chocolates during the weekend only
    - Eat cookies once a month only
    - Butter, only with some soups
    - Cheese, only twice a week
    - Ice-cream, once a month
    - Replace white bread
    - No fast food
    - Avoid juice (because sugars)
    - Avoid sodas (too much sugar)
    - Alcohol (only red wine and beer once every 2 months)
    - Meat, only 180 gr per/week max
  - Nutrition (increase)
    - Fruits
    - Vegetables
    - Salads
    - Eggs (quality 0)
    - Natural juices
    - Smoothies only when doing sport
    - Legumes
    - Seeds
  - Take care of parts of the body
    - Improve arch feet
    - Take care of Elbow tendinitis
    - Take care of Scapula (shoulder blade) muscle contraction
    - Take care of Wrists when doing yoga

* Sport calendar
* Agujetas
  Seguro que a todos más de una vez nos ha dado por hacer deporte después de estar un tiempo inactivos y al día siguiente hemos amanecido con dolores horribles que impiden movernos normalmente. Son las famosas agujetas o científicamente bautizadas como: dolor muscular de origen retardado (DOMS en inglés).
  El mito de que las agujetas son cristales de ácido láctico que pinchan al músculo es erróneo, ya que se ha visto como en personas con la enfermedad de McArdle, incapaces de producir ácido láctico, también sufrían dolor muscular de origen retardado.
  Los actuales estudios apuntan como principal causa a una reacción inflamatoria en respuesta a las microlesiones musculares y tendinosas que se producen al no estar el músculo adaptado a la intensidad del ejercicio. Es decir, el músculo hace un ejercicio de intensidad al que no está acostumbrado, se producen microlesiones musculares y tendinosas, lo que hace que se acumulen gran cantidad de metabolitos o desechos, que dan paso a una reacción inflamatoria e irritan las fibras nerviosas produciendo dolor.
  ¿Cómo tratar las agujetas?
  El dar un vaso de agua con azúcar no sirve para nada, antes se hacía esto porque se pensaba que el agua con azúcar disolvía los cristales que teóricamente pinchaban y producían el dolor. Parece ser que lo más efectivo es el tratamiento con antiinflamatorios no esteroideos (Aines), cremas antiinflamatorias y crioterapia. También el realizar el mismo tipo de ejercicio aumenta el riego sanguíneo en la zona afectada, reduciendo los metabolitos y paliando en cierto grado el dolor.
  Ya sabes, si hace tiempo que no estás activo y mañana quieres ponerte a entrenar, lo primero es realizar un buen calentamiento y empezar con poca intensidad. Si aún así al día siguiente tienes agujetas, tómate te recomendamos un antiinflamatorio para calmar el dolor y realiza el mismo ejercicio a poca intensidad para limpiar tus músculos.
  Es importante recordar que la presencia de agujetas no es indicativo de lesión.
  Como aliviar las agujetas
  Para aliviar las agujetas olvídate de remedios caseros cono agua con azúcar después de hacer de ejercicio para eliminarla, cuanto más entrenes un tipo de deporte determinado, menos las sentirás.
  Aunque el descanso resulta muy importante para superar lesiones, la actividad moderada puede acelerar la recuperación.
  Para aligerar las lesiones y favorecer la recuperación cambia por un ejercicio aeróbico más suave como caminar, nadar, montar en bicicleta, hacer marcha, etc.
  Se aconseja minimizar el dolor con elevación de talones, movimientos de femoral y de los aductores, así como estiramientos de femorales y cuádriceps.
  Uno de los tratamientos más indicados para esta lesión es el masaje, aplicado tras el ejercicio.
  A la vuelta de las vacaciones y el retorno a la actividad deportiva, la mayoría de nosotros solemos experimentar lo que se conoce como agujetas. Se producen por el sometimiento que los músculos sufren de nuevo a la hora de hacer ejercicio y el estrés que éste les provoca. Las agujetas son un síntoma de que el ejercicio está incidiendo en los músculos, pero es importante que sepamos algunas cosas sobre ellas para saber si debemos o no entrenar con agujetas.
