* fluxbox

Configuration in fluxbox requires first the installation:

 $ '''sudo apt-get install fluxbox'''

Later, check the theme or style "carp". After that, modify the fluxbox configuration files following next instructions.

Fluxbox menu, file: '''.fluxbox/menu'''

 [begin] (fluxbox)
      [submenu] (Term)
             [exec] (FunkyShell) { x-terminal-emulator -T "Zsh (snapshot)" -e /bin/zsh-beta} <>
             [exec] (Root) { aterm -tr -trsb +sb -tint black -bg white -e su }
             [exec] (Aterm blue) { aterm -tr -trsb +sb -tint blue -bg white }
             [exec] (Aterm red) { aterm -tr -trsb +sb -tint red -bg white }
             [exec] (Aterm green) { aterm -tr -trsb +sb -tint green -bg white }
             [exec] (Aterm yellow) { aterm -tr -trsb +sb -tint yellow -bg white }
      [end]
      [submenu] (The Editor)
             [exec] (Emacs Server) { aterm -tr -trsb +sb -tint white -bg black -e emacs --daemon }
             [Exec] (Emacs Client) { emacsclient -c }
             [exec] (Emacs load config) { emacs }
             [exec] (Emacs no config) { emacs -q }
             [exec] (Emacs debug) { emacs --debug-init }
             [exec] (Emacs Stop server) { ~/scripts/kill-emacs.sh }
      [end]
      [exec] (Firefox) { firefox }
      [submenu] (Net & Security) {}
         [exec] (TOR) {tor}
         [exec] (GNS3 Network Simulation Tool) {/usr/bin/gns3} # </usr/share/pixmaps/gns3.xpm>
         [exec] (Wireshark) {/usr/bin/wireshark}
         [exec] (Nessus) {/usr/bin/nessus}
         [exec] (Metasploit) {/usr/bin/metasploit}
         [exec] (Tcpdump) {/usr/bin/tcpdump}
         [exec] (Scapy) { x-terminal-emulator -T "Zsh (snapshot)" -e scapy }
      [end]
      [submenu] (Office) {}
         [exec] (LibreOffice Calc) {/usr/bin/libreoffice --calc} </usr/share/icons/hicolor/32x32/apps/libreoffice-calc.xpm>
         [exec] (LibreOffice Impress) {/usr/bin/libreoffice --impress} </usr/share/icons/hicolor/32x32/apps/libreoffice-impress.xpm>
         [exec] (LibreOffice Writer) {/usr/bin/libreoffice --writer} </usr/share/icons/hicolor/32x32/apps/libreoffice-writer.xpm>
         [exec] (LibreOffice Math) {/usr/bin/libreoffice --math} </usr/share/icons/hicolor/32x32/apps/libreoffice-math.xpm>
         [exec] (LibreOffice Draw) {/usr/bin/libreoffice --draw} </usr/share/icons/hicolor/32x32/apps/libreoffice-draw.xpm>
      [end]
      [submenu] (Virtualization)
         [exec] (Virtualbox) {virtualbox}
         [exec] (Qemu) {qemu}
      [end]
      [submenu] (Multimedia)
         [exec] (Okular PDF) {okular}
         [exec] (Pidgin) {pidgin}
         [exec] (Shotwell camera) {shotwell}
         [exec] (RAW Therapee) {rawtherapee}
         [exec] (Dolphin) {dolphin}
         [exec] (Gthumb) {gthumb}
         [exec] (Shutter) {shutter}
         [exec] (Nautilus) {nautilus}
         [exec] (Dia) {dia}
         [exec] (Kdenlive video editor) {kdenlive}
         [exec] (Xine video) {xine}
         [exec] (Screenshot) {xwd -root | convert xwd:- /home/overdrive/screenshot`date +%S_%H_%M_%d_%M_%Y`.png }
      [end]
      [submenu] (Mail)
         [exec] (Thunderbird) {icedove}
         [exec] (Evolution) {evolution}
      [end]
      [submenu] (Space)
         [exec] (Predict) { x-terminal-emulator -T "Zsh (snapshot)" -e predict }
         [exec] (Gpredict) {gpredict}
         [exec] (GSAT) {gsat}
         [exec] (Stellarium) {stellarium}
      [end]
      [submenu] (Settings)
         [config] (Configuration)
         [submenu](wallpapers)
            [wallpapers] (/home/overdrive/all/wallpapers/) {fbsetbg}
         [end]
         [submenu] (Styles) {}
            [stylesdir] (/usr/share/fluxbox/styles)
            [stylesdir] (~/.fluxbox/styles)
         [end]
         [workspaces] (Workspaces)
         [reconfig] (Reconfigure)
         [restart] (Restart)
      [end]
   [exit] (Exit)
 [end]


Fluxbox startup, file: '''.fluxbox/startup'''

 #!/bin/sh
 #
 # fluxbox startup-script:
 #
 # Lines starting with a '#' are ignored.

 # Change your keymap:
 xmodmap "/home/overdrive/.Xmodmap"

 # Applications you want to run with fluxbox.
 # MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
 #
 # unclutter -idle 2 &
 # wmnd &
 # wmsmixer -w &
 # idesk &
 #
 # Debian-local change:
 #   - fbautostart has been added with a quick hack to check to see if it
 #     exists. If it does, we'll start it up by default.
 which fbautostart > /dev/null
 if [ $? -eq 0 ]; then
     fbautostart
 fi

 # Wallpaper
 fbsetbg /home/overdrive/all/Wallpapers/dragon.jpg
 tilda &
 xscreensaver -no-splash &
 root-tail -g 1400x70+100+795 --font '*-*-*-*-*-*-*-*-*-*-*-c*' /var/log/messages,white /var/log/auth.log,white,'ALERT' &
 conky &
 gkrellm &

 # And last but not least we start fluxbox.
 # Because it is the last app you have to run it with ''exec'' before it.

 exec fluxbox
 # or if you want to keep a log:
 # exec fluxbox -log "/home/overdrive/.fluxbox/log"

Fluxbox keybindings, file: '''.fluxbox/keys'''

 # click on the desktop to get menus
 OnDesktop Mouse1 :HideMenus
 OnDesktop Mouse2 :WorkspaceMenu
 OnDesktop Mouse3 :RootMenu

 # scroll on the desktop to change workspaces
 OnDesktop Mouse4 :PrevWorkspace
 OnDesktop Mouse5 :NextWorkspace

 # scroll on the toolbar to change current window
 OnToolbar Mouse4 :PrevWindow {static groups} (iconhidden=no)
 OnToolbar Mouse5 :NextWindow {static groups} (iconhidden=no)

 # alt + left/right click to move/resize a window
 OnWindow Mod1 Mouse1 :MacroCmd {Raise} {Focus} {StartMoving}
 OnWindowBorder Move1 :StartMoving

 OnWindow Mod1 Mouse3 :MacroCmd {Raise} {Focus} {StartResizing NearestCorner}
 OnLeftGrip Move1 :StartResizing bottomleft
 OnRightGrip Move1 :StartResizing bottomright

 # alt + middle click to lower the window
 OnWindow Mod1 Mouse2 :Lower

 # control-click a window's titlebar and drag to attach windows
 OnTitlebar Control Mouse1 :StartTabbing

 # double click on the titlebar to shade
 OnTitlebar Double Mouse1 :Shade

 # left click on the titlebar to move the window
 OnTitlebar Mouse1 :MacroCmd {Raise} {Focus} {ActivateTab}
 OnTitlebar Move1  :StartMoving

 # middle click on the titlebar to lower
 OnTitlebar Mouse2 :Lower

 # right click on the titlebar for a menu of options
 OnTitlebar Mouse3 :WindowMenu

 # alt-tab
 Mod1 Tab :NextWindow {groups} (workspace=[current])
 Mod1 Shift Tab :PrevWindow {groups} (workspace=[current])

 # cycle through tabs in the current window
 Mod4 Tab :NextTab
 Mod4 Shift Tab :PrevTab

 # go to a specific tab in the current window
 Mod4 1 :Tab 1
 Mod4 2 :Tab 2
 Mod4 3 :Tab 3
 Mod4 4 :Tab 4
 Mod4 5 :Tab 5
 Mod4 6 :Tab 6
 Mod4 7 :Tab 7
 Mod4 8 :Tab 8
 Mod4 9 :Tab 9

 # open a terminal
 Mod1 F1 :Exec x-terminal-emulator

 # open a dialog to run programs
 Mod1 F2 :Exec fbrun

 # volume settings, using common keycodes
 # if these don't work, use xev to find out your real keycodes
 176 :Exec amixer sset Master,0 1+
 174 :Exec amixer sset Master,0 1-
 160 :Exec amixer sset Master,0 toggle

 # current window commands
 Mod1 F4 :Close
 Mod1 F5 :Kill
 Mod1 F9 :Minimize
 Mod1 F10 :Maximize
 Mod1 F11 :Fullscreen

 # open the window menu
 Mod1 space :WindowMenu

 # exit fluxbox
 Control Mod1 Delete :Exit

 # change to previous/next workspace
 Control Mod1 Left :PrevWorkspace
 Control Mod1 Right :NextWorkspace

 # send the current window to previous/next workspace
 Mod4 Left :SendToPrevWorkspace
 Mod4 Right :SendToNextWorkspace

 # send the current window and follow it to previous/next workspace
 Control Mod4 Left :TakeToPrevWorkspace
 Control Mod4 Right :TakeToNextWorkspace

 # change to a specific workspace
 Control F1 :Workspace 1
 Control F2 :Workspace 2
 Control F3 :Workspace 3
 Control F4 :Workspace 4
 Control F5 :Workspace 5
 Control F6 :Workspace 6
 Control F7 :Workspace 7
 Control F8 :Workspace 8
 Control F9 :Workspace 9
 Control F10 :Workspace 10
 Control F11 :Workspace 11
 Control F12 :Workspace 12

 # send the current window to a specific workspace
 Mod4 F1 :SendToWorkspace 1
 Mod4 F2 :SendToWorkspace 2
 Mod4 F3 :SendToWorkspace 3
 Mod4 F4 :SendToWorkspace 4
 Mod4 F5 :SendToWorkspace 5
 Mod4 F6 :SendToWorkspace 6
 Mod4 F7 :SendToWorkspace 7
 Mod4 F8 :SendToWorkspace 8
 Mod4 F9 :SendToWorkspace 9
 Mod4 F10 :SendToWorkspace 10
 Mod4 F11 :SendToWorkspace 11
 Mod4 F12 :SendToWorkspace 12

 # send the current window and change to a specific workspace
 Control Mod4 F1 :TakeToWorkspace 1
 Control Mod4 F2 :TakeToWorkspace 2
 Control Mod4 F3 :TakeToWorkspace 3
 Control Mod4 F4 :TakeToWorkspace 4
 Control Mod4 F5 :TakeToWorkspace 5
 Control Mod4 F6 :TakeToWorkspace 6
 Control Mod4 F7 :TakeToWorkspace 7
 Control Mod4 F8 :TakeToWorkspace 8
 Control Mod4 F9 :TakeToWorkspace 9
 Control Mod4 F10 :TakeToWorkspace 10
 Control Mod4 F11 :TakeToWorkspace 11
 Control Mod4 F12 :TakeToWorkspace 12

 # Keys for launch applications
 # (T)erm
 Mod4 T :ExecCommand x-terminal-emulator -e /bin/zsh-beta
 # (B)ash
 Mod4 B :ExecCommand x-terminal-emulator
 # (F)irefox
 Mod4 F :ExecCommand firefox
 # (E)macs
 Mod4 E :ExecCommand emacs
 # (W)indow view, dolphin file manager
 Mod4 W :ExecCommand dolphin
 # (X)lock protect PC
 Mod4 X :ExecCommand i3lock
 # Scrensaver (L)ock
 Mod4 L :ExecCommand xscreensaver-command --lock
 # Next line is additional if only wants to activate the screenshot without locking
 # Mod4 S :ExecCommand xscreensaver-command -activate
 # Emacs (S)erver
 Mod4 S :Exec emacs --daemon
 # Emacs (C)lient
 Mod4 C :ExecCommand emacsclient -c
 # Capture (I)mage screenshot
 Mod4 I :ExecCommand xwd -root -screen > /home/overdrive/screenshot`date +%S_%H_%M_%d_%M_%Y`
 # (R)un commands with bbrun
 Mod4 R :ExecCommand bbrun


Fluxbox init '''.fluxbox/init'''

 Set the background with fbsetbg file.png or
 Fluxbox allows to ignore the background specified in a style file by specifying it in your ~/.fluxbox/init file:
 session.screen0.rootCommand: fbsetbg -f ~/backgrounds/zimdib_dark.png
 To avoid having to change the ~/.fluxbox/init file, fbsetbg will store the used wallpaper in ~/.fluxbox/lastwallpaper and a reload it when called with option -l. The rootCommand should then be.
 Then edit .fluxbox/init and add this line:
 session.screen0.rootCommand: fbsetbg -l

 Ref: http://fluxbox.sourceforge.net/docbook/en/html/chap-bg.html

Additional widgets for fluxbox '''wm widgets''':

 root@apocalipsis:/home/overdrive# apt-cache search wm|grep ^wm*
 wmgui - GUI interface to the wiimote
 wminput - Userspace driver for the wiimote
 wmanx - Manx Gaelic dictionary words for /usr/share/dict
 wmpomme - WindowMaker dockapp client for pommed
 w9wm - enhanced window manager based on 9wm
 wapua - Web browser for WAP WML pages
 wbar - light and fast launch bar
 wdm - WINGs Display Manager - an xdm replacement with a WindowMaker look
 wesnoth-1.10-tools - tools for campaign developers for Wesnoth (branch 1.10)
 wm-icons - Themed icon set that is Window Manager agnostic.
 wm2 - small, unconfigurable window manager
 wmacpi - ACPI battery monitor for WindowMaker
 wmail - WindowMaker docklet watching your inbox
 wmaker - NeXTSTEP-like window manager for X
 wmaker-common - Window Maker - Architecture independent files
 wmaker-dbg - Debugging symbols for WindowMaker packages
 wmaker-data - several free icons for use with WindowMaker and others
 wmaloader - firmware downloader for Linksys WMA11B media adapter
 wmanager - window-manager selection tool used at X startup
 wmauda - remote-control dockapp for Audacious
 wmbattery - display laptop battery info, dockable in WindowMaker
 wmbiff - A dockable app that displays information about mailboxes
 wmbubble - system-load meter for Window Maker that features a duck
 wmbutton - dockapp displaying nine configurable buttons
 wmcalclock - A dock.app which simply tells time and date
 wmcdplay - A CD player based on ascd designed for WindowMaker
 wmclock - dockable clock applet for Window Maker
 wmclockmon - Displays a clock in 12/24h mode with alarm mode
 wmcoincoin - Humourous dockapp for browsing DaCode sites' news and board
 wmcpu - Window Maker docking app similar to xosview
 wmcpuload - Dockapp that displays the current CPU usage
 wmctrl - control an EWMH/NetWM compatible X Window Manager
 wmdate - Calendar for window manager docking bars
 wmdiskmon - dockapp to display disk usage
 wmdrawer - a button launcher
 wmf - Web Mail Folder
 wmforkplop - monitors forking activity and displays top CPU consuming processes
 wmfrog - dockapp for graphically indicating the weather
 wmhdplop - hard drive activity monitor dockapp
 wmifinfo - Dockapp that shows information for all interfaces
 wmifs - WindowMaker dock app for monitoring network traffic
 wmii - lightweight tabbed and tiled X11 window manager, version 3
 wmii-doc - lightweight tabbed and tiled X11 window manager, version 3 (documentation)
 wmitime - clock dock app showing time and internet time
 wmix - Dockapp mixer for OSS
 wml - off-line HTML generation toolkit
 wmlongrun - A program to monitor longrun status
 wmmatrix - View The Matrix in a Window Maker dock application
 wmmemload - WindowMaker dockapp to monitor memory and swap usage
 wmmixer - mixer application designed for WindowMaker
 wmmon - Window Maker dockapp for monitoring system information
 wmmoonclock - WindowMaker moon phase dockapp
 wmnd - Dockapp monitoring network interfaces
 wmnd-snmp - Dockapp monitoring network interfaces with SNMP support
 wmnet - network monitor for WindowMaker
 wmnut - WindowMaker dock app that displays UPS statistics from NUT's upsd
 wmpinboard - Window Maker dock applet resembling a miniature pinboard
 wmppp.app - PPP dial control and network load monitor with NeXTStep look
 wmpuzzle - WindowMaker dock app 4x4 puzzle
 wmrack - Combined CD Player + Mixer designed for WindowMaker
 wmressel - Dock app to change X11 resolutions
 wmshutdown - dockapp to shutdown or reboot your machine
 wmtemp - WM dock applet displaying lm_sensors temperature values
 wmtime - Window Maker dockapp that displays the time and date
 wmtv - Dockable video4linux TV player for WindowMaker
 wmwave - Monitor status of an 802.11 wireless ethernet link
 wmweather - WindowMaker dockapp that shows your current weather
 wmweather+ - WindowMaker dock app that shows your current weather
 wmwork - Keep track of time worked on projects
 wmxmms2 - remote-control dockapp for XMMS2
 wmxres - dock application to select your display mode among those possible
 wap-wml-tools - Wireless Markup Language development and test tools
