* Como nacio el LSD

** Escila

Las sustancias activas de la escila pertenecen al grupo de los glicosidos (sustancias sacariferas) cardioactivas, y sirven igual que las del digital, para el tratamiento del debilitamiento del miocardio. Los glucosidos cardiacos son sustancias altamente activas. Sus dosis terapeutica (curativa) y toxica (venenosa) estan tan proximas que es muy importante una dosificacion exacta con la ayuda de las sustancias puras.

** Cornezuelo de centeno

Historia de la droga con su descripcion clasica:
Monografia G. Barger, Ergot, and Ergotism (Gurney & Jackson, Londres, 1931)

Aspecto quimico:
A. Hofmann, Los alcaloides del cornezuelo de centeno (F. Enke, Stuttgart, 1964)

Aplicacion medica:
John Stearns, Account of the pulvis parturiens, a Remedy for Quickenning Child-Birth.

Aislar y caracterizar el componente fundamental comun a todos los alcaloides del cornezuelo, lo llamaron acido lisergico. Mas tarde marco un progreso importante tanto quimico como medico, el aislamiento del principio hemostatico del cornezuelo que actua especificamente sobre el utero. Estos resultados fueron publicados simultaneamente por 4 institutos independientes entre si.

* El LSD en la experimentacion con animales y en la investigacion biologica

Una medida para la toxicidad de una sustancia es la LDₓ, esto es, la dosis a la que muere el 50% de los animales tratados. En general varia mucho segun la especie animal, y asi tambien ocurre con el LSD.

Raton: LDₓ = 50-60 mg/kg (50-60 milesimas de gramo por cada kilogramo del peso del animal)
Rata: LDₓ = 16.5 mg/kg
Conejo: LDₓ = 0.3 mg/kg
Elefante: LDₓ = 0.06 mg/kg

Pero si se compara la dosis mortal para los animales con la dosis activa en el hombre, que es de 0.003 a 0.001 mg/kg, resulta una excelente tolerancia para el LSD. Una dosis 50.000-100.000 veces mayor que la dosis toxica para el raton tendrian consecuencias mortales en el hombre.

Pronto se mostro que tambien ciertos derivados del LSD, unos compuestos en los que la estructura quimica del LSD esta apenas modificada, y que no presentan propiedades alucinogenas, impiden los efectos de la serotonina tanto o mas que el LSD puro. Por lo tanto, el efecto bloqueador de la serotonina por parte del LSD no basta para explicar sus propiedades alucinogenas.

El LSD tambien influye en funciones neurofisiologicas conectadas con la dopamina, una sustancia tambien de tipo hormonal de origen natural. La mayoria de los centros cerebrales que responden a la dopamina se activan con el LSD, otros se ven amortiguados.

* Derivados quimicos del LSD

Los resultados de la derivacion quimica del LSD fueron valiosos para la investigacion farmacologica al hallarse derivados que eran apenas o nada alucinogenos, y que en cambio presentaban intensificados otros efectos del LSD. Uno de ellos es un efecto bloqueador de la neurohormona serotonina. Como la serotonina cumple un papel en los procesos alergico-inflamatorios y tambien en el origen de la migrana, una sustancia especificamente bloqueadora de la serotonina es muy importante para la medicina.

* La aplicacion del LSD en psiquiatria

Schweizer Archiv fur Neurologie und Psychiatrie (Archivo Suizo de Neurologia y Psiquiatria), 1947. Dr. Werner A. Stoll

Phantastica, L. Lewin

Der Meskalinrausch (La embriaguez de mescalina) K. Beringer.

Lo novedoso del LSD frente a la mescalina era la elevada eficacia, que se movia en otro orden. A la dosis activa de 0.2-0.5 g de mescalina se contrapone la de 0.00002-0001 g de LSD. Es decir, que el LSD es 5.000-10.000 veces mas activo que la mescalina.

Los efectos psiquicos del LSD, generados por cantidades tan infimas de sustancia, son demasiado significativos y multiformes para que puedan explicarse a traves de cambios toxicos de las funciones cerebrales. Si solo se tratara de un efecto toxico en el cerebro, las experiencias con LSD no tendrian una importancia psicologica y psiquiatrica, sino solo piscopatologica. Teniendo una influencia sobre las conexiones transversales y sinapsis entre las celulas cerebrales.

La aplicacion del LSD para el relajamiento animico en la psicoterapia analitica se basa sobre todo en los efectos de:

 - Relajacion o surpresion de la barrera yo/tu. Pueda servir para la problematica egocentrica y desprenderse de la fijacion y su aislamiento, estableciendo un mayor contacto entre medico y paciente, teniendo una mayor inflenciabilidad bajo los efectos del LSD.

- Psicoterapeuticamente para recuperar experiencias olvidadas o reprimidas.
- El LSD no actua como un verdadero medicamento, sino que cumple el papel de un recurso medicamentoso en el marco del un tratamiento psicoanalitico y psicoterapeutico, capaz de dar mayor eficacia y menor duracion a dicho tratamiento, aplicado de dos formas distintas:
  - Terapia psicolitica (psycholytic therapy): solucion de tensiones o conflictos en la psique humana.
  - Terapia psicodelica (psychedelic therapy): mediante desencadenar shock de LSD una experiencia mistico-religiosa que pueda servir para tratamiento psicoterapeutico para una reestructuracion y cura de la personalidad del paciente.
- El aprovechamiento del LSD como recurso medicamentoso en psicoanalisis y psicoterapia se basa en efectos opuestos a los que provocan los psicofarmacos del tipo de los tranquilizantes. Mientras que estos mas bien tapan los problemas y conflictos del paciente, de modo que parezcan menos graves e importantes, el LSD por el contrario, los pone al descubierto; exponiendolos con mayor nitidez y tornandose mas accesible al tratamiento psicoterapeutico.
- Lo mismo vale para otros procedimientos empleados en psiquiatria, como el electrochoque, la insulinoterapia o la psicoquirurgia, cuya aplicacion encierra ademas, un riesgo mucho mayor que la del LSD. El empleo del LSD en condiciones apropiadas puede considerarse practicamente inocuo.
- Administracion a moribundos, mostrando dolores muy fuertes a enfermos de cancer que ya no respondian a analgesicos convencionales, eran atenuados o eliminados totalmente por el LSD.

The human encounter with Death (El encuentro del hombre con la muerte) de Stanislav Grof y J. Halifax

Realms of the Human Unconscious. Observations from LSD Research (El inconsciente humano, observaciones sobre los estudios con LSD de Stanislav Grof.

* De medicamento a droga narcotica

Robert E. L. Masters y Jean Houston: Phychedelic Art (Arte Psicodelico)

Richard P. Hartmann, Malerei aus Bereichen des Unbewussten. Kunstler experimentieren unter LSD (Pintura del ambito de lo inconsciente. Artistas experimentar bajo el LSD)

Segun lo aseveraban a menudo observadores superficiales, sino tiene profundas causas sociologicas. Son estas: el materialismo, el alejamiento de la naturaleza a consecuencia de la industrializacion y la vida urbana, la insuficiente satisfaccion en la actividad profesional en un mundo del trabajo mecanizado y desalmado, el aburrimiento y la falta de objetivos en una sociedad de bienestar saturada, asi como la falta de un motivo vital religioso, protector y coherente como concepcion de mundo.

Revista medica: Mac Lean's Canada National Maganize, "Mis doce horas loco", Sidney Katz

Revista alemana: Quick, publico en 1954 un reportaje sensacionalista sobre "Un osado experimento cientifico" del pintor Wilfred Zeller

Revista norteamericana Look, publico en 1959 "The curious story behind the new Cary Grant" (La extrana historia que hay detras del nuevo Cary Grant)

Exploring Inner Space (Explorando el espacio interior) de Jane Dunlap, y My Self and I (Yo y yo misma) de Constance A. Newland.

Desde luego, tambien publicaron libros objetivos, esclarecedores, sobre el LSD y su problematica, como el excelente escrito del psiquiatra Dr. Sidney Cohen, The Beyond Within (El mas alla interior)

* Peligros de los ensayos no medicos con LSD

Los que abogan por un consumo no controlado, libre, de LSD y otros alucinogenos, fundamentan su postura en que este tipo de drogas no genera adiccion, y en que con un consumo moderado hasta ahora no ha podido demostrarse que los alucinogenos hayan ocasionado perjuicios a la salud. Ambas afirmaciones son ciertas. Jamas ha podido observarse que ni siquiera con un consumo frecuente y prolongado de LSD se generara una verdadera mania, que se caracteriza porque al quitarse la sustancia aparecen perturbaciones psiquicas y a menudo tambien disfuncionamientos fisicos graves. No se conocen aun danos organicos ni casos fatales como consecuencia directa de una intoxicacion de LSD. Una sustancia poco toxica en comparacion con su efectividad psiquica extremadamente elevada.

Pero el LSD, al igual que los demas alucinogenos, ofrece otro tipo de peligros. Mientras que en los estupefacientes que crean toxicomania, en los opiaceos, las anfetaminas, etc, los perjucios psiquicos y fisicos aparecen solo con un uso cronico, el LSD es peligroso en cada ensayo singular, pues pueden aparecer delirios graves. Estos incidentes pueden evitarse en gran medida con una preparacion interna y externa adecuada de los experimentos y nunca hay que excluir el factor de seguridad. Las crisis de LSD semejan ataques psicoticos con caracter maniaco o depresivo.

En un estado maniaco, hiperactivo, el sentimiento de omnipotencia o de invulnerabilidad puede acarrear accidentes graves. El peligro de desencadenar una reaccion psicotica es especialmente grande cuando se le suministra LSD a una persona sin su conocimiento. 

Una naturaleza distinta la presentan peligros cuando el delirio desdencadenado por el LSD no es de caracter maniaco, sino depresivo. En estos casos, las visiones aterradoras, el miedo mortal o el miedo a estar o volverse loco pueden llevar a peligrosos colapsos psiquicos y al suicidio.

* El caso del Dr. Leary

Leary distinguia con total claridad las drogas psicodelicas -LSD, psilocybina, mescalina, hachis-, de cuyos efectos beneficiosos estaba convencido, de estupefacientes conducentes a la toxicomania: morfina, heroina, etc, y alertaba repetidamente contra el uso de estos ultimos.

* Viajes al cosmos del alma

William Blake, Doors of perception (Puertas de la percepcion)

Las puertas de la Percepcion, Aldous Huxley

El fenomeno LSD, John Cashman

* Los parientes mexicanos del LSD

La seta sagrada teonanacatl: No se conocia entonces ninguna otra droga que provocara alucinaciones como el LSD, salvo el cactus de la mescalina, que tambien existia en Mexico.

Mushrooms, Russia and History (Setas, Rusia y la Historia), Valentina Pavlovna y R. Gordon Wasson

Historia general de las cosas de Nueva Espana. Bernardino de Sahagun

La dosis activa media de psilocybina o psilocina en el hombre es de 0.01 g (diez miligramos), con lo que estas sustancias son 100 veces menos activas que el LSD, en el que 0.1 miligramos constituyen una dosis fuerte. Ademas, la duuracion del efecto de las sustancias de las setas es menor que la del LSD: es de 4 a 6 horas, mientras que en el LSD es de 8 a 12 horas.

"La enredadera magica" (ololiuqui) en su Excelente estudio sobre los aspectos historicos, etnologicos y botanicos del ololiuqui: Dr. R. Evans Schultes, A contribution to our knowledge of Rivea corymbosa. The narcotic ololiuqui of the aztecs (Una contribucion a nuestro conocimiento de la Rivea corymbosa, el ololiuqui narcotico de los aztecas).

Rerum Medicarum Novae Hispaniae Tresaurus Seu Plantarum, Animalium, Mineralium Mexicanorum Historia, 1651. Francisco Fernandez

* La busqueda de la planta magica Ska Maria Pastora

Die kunstlich gesteurte Seele (El alma artificialmente dirigida), Klaus Thomas

* La irradiacion de Ernst Junger

Ernst Junger, El corazon aventurero

Ernst Junger, Sobre los acantilados de marmol

Textos sobre su nuevo "phan-tasticun" y "Confesiones de un ingles comedor de opio". Kirchhorst

A mi juicio, el te es un phantasticun, el cafe un energeticum. Por eso el te posee un rango de sensibilidad artistica incomparablemente mayor. Con el cafe me doy cuenta de que destruye la tenue red de luz y sombras, las dudas fructiferas que se presentan mientras se escribe una oracion. Uno aplasta sus inhibiciones. Con el te, por el contrario, los pensamientos se van engarzando de modo genuino.

Heliopolis, Antonio Peri

Vision retrospectiva de una ciudad

"Las puertas de la percepcion" y Heaven and Hell (El cielo y el infierno), Aldous Huxley

Visita a Godenholm, Junger

Die Narkotischen Genussmittel und der Mensch (Los estimulantes narcoticos y el hombre)

Alexander von Humboldt, Del Orinoco al Amazonas: viaje a las regiones equinocciales del Nuevo Continente (Libro 8, capitulo 24)

Orinoco Ilustrado, 1741, P.J. Gumilla

Las sustancias activas altamente psicotropicas como el LSD y la psilocybina, tienen en su estructura quimica un parentesco muy estrecho con sustancias que existen en el cuerpo, que presentan en el sistema nervioso central y cumplen un papel importante en la regulacion de sus funciones. Es dable por tanto pensar que por alguna perturbacion en el metabolismo se forme, en vez de la neurohormona normal, algun compuesto del tipo del LSD o de la psilocybina que pueda modificar y determinar el caracter de la personalidad, su vision del mundo y su actuar.

Gottfried Benn, Provoziertes Leben (Vida provocada)

D.T. Suzuki, El zen y la cultura japonesa

Acercamientos: drogas y ebriedad, Ernst Junger, 1970

El farmacologo senalo: "Ahora comprendo por que estaba usted sentado en el sillon sin su cabeza; me sorprendi; no puedo haberme equivocado". Me pregunto si no debiera tachar ese detalle, porque cumple con los requisitos de los cuentos de aparecidos. (Con embriagadez de psilocybina, que tiene un caracter mas tetrico que el LSD).

Diario de navegacion: "Acercamientos: drogas y ebriedad"

Bastaba una mirada para obtener un entendimiento sin palabras, sin embargo, fragmentos de las oraciones al comienzo fueron: "Nuestra barca se mueve mucho".

* Encuentro con Aldous Huxley

Huxley ve el valor de las drogas alucinogenas en el hecho de que permiten que personas que no posean el don de la contemplacion visionaria espontanea, propia de los misticos, los santos y los grandes artistas, puedan experimentar ellos mismos estos extraordinarios estados de la conciencia. Esto llevaria a una comprension mas profunda de los contenidos religiosos o misticos a una experiencia novedosa de las grandes obras de arte. Estas drogas son para Huxley las llaves que permiten abrir nuevas puertas de la percepcion, llaves quimicas que coexisten con otros "abridores de puertas" consagrados pero mas laboriosos, como la meditacion, el aislamiento y el ayuno, o como ciertos ejercicios de yoga.

Un mundo feliz, Aldous Huxley, 1932

La isla, Aldous Huxley

Volumen II de la WAAS bajo el titulo de "The population crisis and the use of world resources (La crisis de la poblacion y el uso de los recursos mundiales), 1965

* Visitas de todo el mundo

La filosofia perenne, en el que se recogen testimonios de una vision iluminada de todos los tiempos y culturas. Huxley escribe que no son lis misticos y los santos, sino tambien muchas mas personas de lo que habitualmente se supone, experimentan tales instantes de dicha, pero que la mayoria de ellas no reconoce su significacion y los reprimen porque no caben en el mundo de la razon cotidiana, en vez de considerarlos como lo que son, momentos providenciales.

* LSD: vivencias y realidad

En la capacidad de sintonizar el receptor "yo" en otras longitudes de onda y asu provocar modificaciones en la consciencia de realidad reside la verdadera significacion del LSD y de los alucinogenos con el emparentados. Esta capacidad de hacer surgir nuevas imagenes de la realidad, esta potencia verdaderamente cosmogonica, vuelve tambien comprensible la adoracion y el cultuo de las plantas alucinogenas como drogas sagradas.

Mystik religios und profan (Mistica religiosa y profana), R. C. Zaehner

Nietszsche, El nacimiento de la tragedia

Eleusis, Schocken Books, 1977. Kerenyi

Por tanto, le meditacion no significa un rechazo de la realidad objetiva, sino que, por el contrario, consiste en una penetracion mas profunda y cognoscitiva, no es la huida al mundo onirico imaginario, sino que busca su verdad mas abrumadora a traves de una observacion simultanea y estereoscopica de la superficie y la profundidad de la realidad objetiva.

De ello tendria que surgir una nueva conciencia acerca de la realidad. Esta podria convertirse en el fundamento de una nueva religiosidad que no se basara en la creencia en los dogmas de las diversas religiones, sino en conocer a traves del <Espiritu de la verdad>. Me refiero a un conocer, un leer y un entender de primera mano "El libro que ha escrito el dedo de Dios" (Paracelso): de la creacion.

